### ISSUE TITLE
文件夹名称不能包含某些字符，导致下载失败

### ISSUE THREAD

**Issue by iscelor** [Mapaler/PixivUserBatchDownload#1]
文件夹名称中不能出现像: < > ? 这些字符，而P站有些名字中有这些字符，导致下载失败

**Comment by Mapaler** [comment]
现在版本你可以去设置里手动修改文件夹名之后下载特殊文件夹，自动命名的解决程序，等我后面来改。
你觉得这些字符怎么解决比较好呢，是全部删掉，还是替换成下划线还是空格什么的？

**Comment by iscelor** [comment]
我觉得替换成下划线好一些。 感谢回答

**Comment by Mapaler** [comment]
已更新

**Comment by river1** [comment]
现在保存会是每个字符前都有个下划线
像这样
_4_1_0_2_6_7_3_8_p__0_._j_p_g

**Comment by river1** [comment]
另一种思路
因为文件名不允许的就下面几个
\ / : * ? " < > |
可以用半角转全角
＼／：＊？＂＜＞｜
替换掉

**Comment by Mapaler** [comment]
等将来可以改成自定义替换字符？
