### ISSUE TITLE
现在好像已不能使用，懒得开发

### ISSUE THREAD

**Issue by Mapaler** [Mapaler/PixivUserBatchDownload#10]
今天测试了一下不能用了，原因是P站直接返回空页面。于是网上找了一下，找到了PixivPy，研究了一下人家的实现方式。基本原理已经搞明白，但是得推倒从头开发。~~但是我目前没什么时间，不会马上出来。~~
有好多现成的工具，干嘛还要自己开发。而且本地的能完成好多JS完成不了的事情。
https://github.com/Nandaka/PixivUtil2

**Comment by lich13** [comment]
期待菊苣有空可以修复下 现在已经重度依赖了 nandaka那个不能多线程自动分目录下载 感觉只有下新图好用

**Comment by Mapaler** [comment]
@lich13 有开发计划，但是最近没时间。
