### ISSUE TITLE
按钮不显示

### ISSUE THREAD

**Issue by Reather17** [Mapaler/PixivUserBatchDownload#102]
前两天正常使用,8.2开始在图片详情页右边画师信息下面不显示按钮了,画师页面下按钮位置从右边变成了左边(虽然没什么影响)

![image](https://user-images.githubusercontent.com/44076117/182304200-0f2961fa-f20d-4d39-b970-e5cec56fb7b7.png)
![image](https://user-images.githubusercontent.com/44076117/182304148-6e3f3094-d5f2-46b3-8bd6-62110be92364.png)

**Comment by Mapaler** [comment]
> 前两天正常使用,8.2开始在图片详情页右边画师信息下面不显示按钮了,画师页面下按钮位置从右边变成了左边(虽然没什么影响)
> 
> ![image](https://user-images.githubusercontent.com/44076117/182304200-0f2961fa-f20d-4d39-b970-e5cec56fb7b7.png) ![image](https://user-images.githubusercontent.com/44076117/182304148-6e3f3094-d5f2-46b3-8bd6-62110be92364.png)

P站框架调整，可以先用按钮菜单里的入口。

**Comment by Reather17** [comment]
129行再加一个div就可以显示了:
	':scope>div>div>div>aside>section', //作品页

**Comment by Mapaler** [comment]
你是在我刚上传的新版本的基础上改的吗？
我是测试了正常使用才上传的，我们的结构有不同吗？

**Comment by Reather17** [comment]
> 你是在我刚上传的新版本的基础上改的吗？
> 我是测试了正常使用才上传的，我们的结构有不同吗？

在之前版本上改的，因为我这刚才没有加载出更新，结构应该是差不多的

**Comment by Mapaler** [comment]
我刚才又改了以下之前没改到的地方。
并把路径代码片段提前了方便改。
多写了一点注释。

路径全部改成新的了，你可以用最新版本看看。

**Comment by Reather17** [comment]
> 我刚才又改了以下之前没改到的地方。
> 并把路径代码片段提前了方便改。
> 多写了一点注释。
> 
> 路径全部改成新的了，你可以用最新版本看看。

好的，感谢🙏
