### ISSUE TITLE
PUBD按钮不显示的一种解决方法

### ISSUE THREAD

**Issue by amwangfan** [Mapaler/PixivUserBatchDownload#103]
或许可以考虑将
`// @resource	pubd-style https://github.com/Mapaler/PixivUserBatchDownload/raw/master/PixivUserBatchDownload%20ui.css?v=5.17.138`
改为
`// @resource	pubd-style https://raw.githubusercontent.com/Mapaler/PixivUserBatchDownload/master/PixivUserBatchDownload%20ui.css?v=5.17.138`
等其他类似的github加速服务
要不加载不出按钮反复刷新太折磨(┬┬﹏┬┬)

**Comment by Mapaler** [comment]
这个CSS获取后是会储存到本地加载的，只要不更新就不需要再次获取。

不显示按钮的原因是因为Pixiv现在是vue框架写的单页面应用，会不断更改页面的源代码，我加载的按钮会很快被更改页面的时候给一并删除。

别的同类应用的解决办法是直接将按钮全局置顶，这样不管换什么页面都会固定显示在最上方。但是我不惜太喜欢，还是希望能融入页面中，就无法解决这个问题（以前老P站没问题）。

建议你直接用在Tampermonkey扩展菜单里面添加的功能入口。

**Comment by amwangfan** [comment]
原来如此，主要是我把resource改成fastgit的之后刷新了一下就好使了，没想到问题在这

**Comment by Elysia7** [comment]
这个问题我也遇到了，改resource没有解决，使用在Tampermonkey扩展菜单里面添加的功能入口默认全部下载，但是我只要一张图这该如何是好呀。 @Mapaler

**Comment by Mapaler** [comment]
> 这个问题我也遇到了，改resource没有解决，使用在Tampermonkey扩展菜单里面添加的功能入口默认全部下载，但是我只要一张图这该如何是好呀。 @Mapaler 

刷新页面试试？vue结构总是变化，我自己也经常遇到这种问题，但是靠我的技术无法解决。
