### ISSUE TITLE
请问可以根据作者发布的标题及目录分开文件夹下载吗？

### ISSUE THREAD

**Issue by hanzong92** [Mapaler/PixivUserBatchDownload#104]
现在ms是所有文件下载到一个文件夹啊，请问可以实现标题中的功能吗，就是按作者发布的标题自动创建文件夹下载，谢谢dalao们！！

**Comment by Mapaler** [comment]
请参考 #34

**Comment by hanzong92** [comment]
> 请参考 #34
> 
> 你可以使用文本输出模式测试掩码输出效果

大佬您这回答太深奥了我看不懂啊，能用通俗点的语言形容下吗
