### ISSUE TITLE
如何查看illust对象

### ISSUE THREAD

**Issue by puinpuni** [Mapaler/PixivUserBatchDownload#105]
只学过一点C++的小白产生的疑问：
原教程中这样写到：
illust对象示例
illust 返回当前目标图片的信息。可使用“下载当前作品”功能，在浏览器开发者控制台查看该作品的illust对象

我在chrome中F12后只在Source中找到这种信息：
 <meta name="preload-data" id="meta-preload-data" content='{"timestamp":"2023-06-28T09:29:18+09:00","illust":{"81806098":{"illustId":"81806098","illustTitle":"2020.05.24","illustComment":"pizza time","id":"81806098","title":"2020.05.24",巴拉巴拉
这里的illust对象中那个key和教程中的不一样，请问教程中的illust对象是怎么找到的呢？
顺带一提：我原本研究这个的目的是想根据作品的收藏或者点赞或者浏览量 筛选要下载的作品
希望大佬帮忙解惑，自找资料两天了，仍没有我很满意的答案

**Comment by Mapaler** [comment]
因为内容比较多，所以只针对“下载当前作品”这个少用功能而不是“下载当前作者”实现。
你需要进入一个单独插画，并用只下载当前作品功能获取数据，才会发送到控制台。

**Comment by puinpuni** [comment]
![image](https://github.com/Mapaler/PixivUserBatchDownload/assets/49758099/d027380f-2139-4345-8356-6e772d1d1011)
是这样的，我想问的是教程中，图上的数据结构我怎么在浏览器中查看

**Comment by Mapaler** [comment]
因为下载作者功能很常用，为了避免被垃圾信息干扰，所以我没有输出对象内容。
你需要找一个作品，选择“下载当前作品”功能。
![firefox_0006](https://github.com/Mapaler/PixivUserBatchDownload/assets/6565860/5aa7b6b1-d93b-4972-afb6-23f80b10ba5d)
然后获取到信息后就会在控制台输出当前作品的对象信息
![firefox_0007](https://github.com/Mapaler/PixivUserBatchDownload/assets/6565860/81305178-751d-4997-b479-f86e8aaf977e)
除了直接在浏览器内查看，也可以选择复制对象到任意代码编辑器内使用
![Notepad2_0009](https://github.com/Mapaler/PixivUserBatchDownload/assets/6565860/d2680485-4bcc-46fd-bba2-553f0f85f8ce)

**Comment by puinpuni** [comment]
谢谢大佬，我能看到了，有收藏，评论，浏览量
