### ISSUE TITLE
完全无法显示下载按钮了

### ISSUE THREAD

**Issue by tooyangtoonaive** [Mapaler/PixivUserBatchDownload#108]
firefox 91.13.0esr。
从扩展菜单点击"下载该画师"，弹出菜单一直无进展

![123](https://github.com/Mapaler/PixivUserBatchDownload/assets/19810827/9e916276-4e28-4705-be54-d267a60b0726)

**Comment by Mapaler** [comment]
![firefox_0148](https://github.com/Mapaler/PixivUserBatchDownload/assets/6565860/ef39700e-a015-49e2-9399-be48947eda9a)
如果你没有勾选自动获取，那么需要自己手动点“他的作品”才会开始获取数据。
