### ISSUE TITLE
v5.0开发计划

### ISSUE THREAD

**Issue by Mapaler** [Mapaler/PixivUserBatchDownload#11]
Q:为什么跳过4.0？
A:4.0计划其实之前在3.0的时候已经有了，但是因为P站改版导致化为泡影，于是直接跳到新的计划。

Q:什么时候能出来？
A:以三次元工作为优先，毕竟要养家。目前三次元有比较重要的事情排在前面。

Q:5.0版原理，能用多久？
A:1~3版都是解析的桌面版网页，通过研究阅读，准备采用[PixivPy](https://github.com/upbit/pixivpy)的方式，里用P站手机APP使用的API进行，因此到时即便你的网页端也登陆了，也需要在我的脚本里用账户密码登录来获取APP使用的Token，好处就是这个API应该改得不是那么快，所以可能脚本能用比较久。另外准备暂时放弃V3.0加入的自定义文件夹功能，优先完成下载功能。

Q:在哪里看新版的开发进度？
A:查看最新的开发进度<del>https://github.com/Mapaler/PixivUserBatchDownload/tree/develop_v5</del>已合并到[Master](https://github.com/Mapaler/PixivUserBatchDownload)

**Comment by Mapaler** [comment]
![image 4](https://cloud.githubusercontent.com/assets/6565860/21570547/cd39b698-cf01-11e6-8f8c-f91276924b67.png)
就是手贱，还是开始写了，今天做出了一点UI的基础。

**Comment by Mapaler** [comment]
![image 5](https://cloud.githubusercontent.com/assets/6565860/21572980/7f885fa8-cf1a-11e6-9d3b-64417d61da9b.png)
熬夜这么久已经累了

**Comment by Mapaler** [comment]
![image 8](https://cloud.githubusercontent.com/assets/6565860/21578793/a33349aa-cfc8-11e6-949d-a16da9b9eaa3.png)
调整UI更让人感觉上瘾啊

**Comment by Mapaler** [comment]
![image 3](https://cloud.githubusercontent.com/assets/6565860/21604437/1dc0951c-d1de-11e6-82bb-ae55ea2bfdde.png)
进一步完善了视窗模拟

**Comment by Mapaler** [comment]
![image 1](https://cloud.githubusercontent.com/assets/6565860/21639670/38200e64-d2ac-11e6-94fb-38b235c38400.png)

**Comment by Mapaler** [comment]
之前以为新的PAPI原来都已经不是那么新了，都已经出Bug了，我得推倒重来，换最新的app-api

**Comment by lzh890208** [comment]
P站改版了，这点应该不会错
https://greasyfork.org/zh-CN/forum/discussion/13633/x
这脚本的第二页出问题了
其中那个书签能用，不知道可不可以参考

**Comment by Mapaler** [comment]
我这次是直接用P站官方手机客户端的API来写，几乎不受网页版影响了，当然为了方便还是需要网页版读取很少的信息。另外我是用原生JS写的，没用JQ。但是目前是完全的推倒重来，原来的代码复用率不到1%，开发很慢，慢慢等吧。

**Comment by Mapaler** [comment]
一大早起来考试好累好困啊，好想睡觉，谁来帮我设计一下逻辑和UI啊

**Comment by Mapaler** [comment]
因为更换了API版本，信息获取又得完全重写

**Comment by Mapaler** [comment]
因为更换了API版本，所有信息获取相关的又得完全重写

**Comment by Mapaler** [comment]
终于把新版APP-API的信息获取做好了。
https://github.com/upbit/pixivpy/issues/29
获取收藏信息这一块，看起来和作品一样，但是涉及到的各种异常情况真是太多了。

**Comment by Mapaler** [comment]
今天才了解到ES5的一些新特性，还得慢慢学习，应该能减少程序的复杂度才对。

**Comment by Mapaler** [comment]
Object.creat() 对于我这种没学过体系的业余爱好者还是较难理解。暂时先不管这个了，先还是用复杂的方法解决。把下载完成了再说。

**Comment by Mapaler** [comment]
好像现在已经可以用了？

**Comment by Mapaler** [comment]
诚招小白鼠，体验，找优先级BUG

**Comment by lzh890208** [comment]
モルモット来た，脚本呢？

**Comment by Mapaler** [comment]
モルモット来た是什么意思？脚本进入develop_v5分支获取吧。看一楼。

**Comment by lzh890208** [comment]
モルモット就是小白鼠呀
你需要这个划词的https://greasyfork.org/scripts/16203/
UI的话还有这个https://github.com/mayswind/AriaNg/blob/master/README-CHS.md
不过如果用了禁了COOKIE就会卡死
试了下可以用
token过时会去掉本来见面的登录状态呢

**Comment by Mapaler** [comment]
我已经把v5分支合并到主分支了，v5分支不更新了。最好去对应的脚本网站来安装，这样油猴支持自动更新。

今天一天都在写文档，现在文档大体

**Comment by Mapaler** [comment]
完成了，看文档就知道怎么进行自定义文件名了。

--------

马德，路上又有2G信号干扰，LG G4屏幕又乱跳，给我点了关闭。

**Comment by Mapaler** [comment]
那个AiraNg看起来好像很不错的样子，回去试试看，到时候加到说明里去。

**Comment by Mapaler** [comment]
禁用cookie卡死是因为为了模拟手机登录的所有信息，我把cookie里的device也读取发送出去了，其实好像不是必须的，你需要禁用cookie吗？

**Comment by Mapaler** [comment]
token登陆毕竟也是使用的同一个浏览器模拟，登录的同时就是把网页版的session换成了pubd登陆的那个，所以一掉网页版的也掉了。
