### ISSUE TITLE
“下载该画师所有作品”功能可能存在问题

### ISSUE THREAD

**Issue by ixoxxoxi** [Mapaler/PixivUserBatchDownload#111]
使用"下载当前作品"可以在几秒内获取到结果并正常通过aria2下载；
但是使用"下载该画师所有作品"功能，等待十几分钟也没有获取到，进程日志框中没有出现任何文字提示。

插件版本：v5.20.147
浏览器版本：Firefox: 102.0  Chromium:102.0.5005.167

**Comment by ixoxxoxi** [comment]
我的问题，弹窗后需要再次点击单选按钮才会获取

**Comment by Mapaler** [comment]
设置里勾上自动获取即可
