### ISSUE TITLE
是否有什么手段批量下载

### ISSUE THREAD

**Issue by 1223334444abc** [Mapaler/PixivUserBatchDownload#112]
感谢您的项目！这几年一直都用PUBD下载，但是日积月累下载的画师越来越多，已经高达好几百，手动下载变得非常痛苦。

尝试转移至其它工具，但都没有能实现输出与PUBD完全一致的工具（主要是动图的存储）；此外有些工具需要手打代码门槛实在太高。（一但转移，本地上百g的数据很难处理归档）

我这边整理有类似这样的表格，不知道有没有批量运行的手段（顺便解决画师名称与id的对应问题）？（一个个运行也可以，同时每次下载将“文本输出”的内容以当天日期为文件名保存至画师文件夹）←目前每次都是手动执行
```
14123418|AAA
2432407|BBBBB
5612494|24FFFF
13712391|46AAA
5666259|98♂♂♂
2354690|433
```

**Comment by Mapaler** [comment]
如果会编程可以直接参考 https://github.com/upbit/pixivpy 进行开发，我这个获取数据的基本原理一样的，都是请求手机APP的API。

PUBD本身前几年为了实现多画师批量下载，同时为了节省请求，我是考虑用本地数据库储存数据的，但是后来因为个人只是基于兴趣导向的业余开发者，的能力不足就搁置了，再加上没使用动力了就没继续开发新功能了。
开发了几年其他项目后，现在觉得这个的代码太老了，要我继续开发，都让我我更想从头再来过了，更没动力。

----

关于自动保存文本文件

因为调用的aria2来下载，aria2没有直接保存指定文件的功能，类似的功能是用来上传种子的。v3.0的时候就用来生成自定义文件的，只能保存成hash码.torrent的格式，所以我需要额外运行一个脚本，来将它转换成desktop.ini，来实现文件夹显示为作者头像，文件夹名显示为作者名称。

![](https://camo.githubusercontent.com/588b214fde837493d45e51feb5747add707469adbf645207a0ae0bd8836b198e/687474703a2f2f7777332e73696e61696d672e636e2f6c617267652f36633834623264366777316633306d7063346835666a32306e623067373434302e6a7067)

很多人并不是发送到本地的Aria2，而是发送到nas上面去，这个仅对Windows有用并且需要额外手动执行功能本地代码的试验功能就废弃了。

**Comment by 1223334444abc** [comment]
要是会编程就好了（扶额.jpg）
这几年用下来还是PUBD最省心，最开始也是从OX163转移过来的

https://github.com/mikf/gallery-dl/issues/4704
这几天在研究转向gallery-dl批量下载
这门槛实在是太高了（扶额.jpg）
主要还是似乎没法实现与PUBD一致的动图处理，它是要么直接下zip，要么编为视频，且不考虑中间延迟值

攒了太多数据 换工具就是大折磨
实在不行还是继续手动撸了.......
（小小吐槽一下）

**Comment by 1223334444abc** [comment]
要是会编程就好了（扶额.jpg）
这几年用下来还是PUBD最省心，最开始也是从OX163转移过来的

`https://github.com/mikf/gallery-dl/issues/4704`
这几天在研究转向gallery-dl批量下载
这门槛实在是太高了（扶额.jpg）
主要还是似乎没法实现与PUBD一致的动图处理，它是要么直接下zip，要么编为视频，且不考虑中间延迟值

攒了太多数据 换工具就是大折磨
实在不行还是继续手动撸了.......
（小小吐槽一下）
以及文件夹图片我甚至是手动指定的（

**Comment by Mapaler** [comment]
对于我，就是Aria2限制了后端操作，起早就构思过考虑帧率的动图处理，但是需要额外编写一个后端程序，没有现成的跨平台解决方案。如果自己搭建一个服务器后端，又需要花我的钱。
