### ISSUE TITLE
动图是否可以打包成zip格式再下载

### ISSUE THREAD

**Issue by bddbnet** [Mapaler/PixivUserBatchDownload#12]
动图太多严重影响下载效率

**Comment by Mapaler** [comment]
以前是下的zip，但是现在找到了原图链接，我就下原图了。zip是压缩转换成jpg的，原图可以是透明png的。下载原图可以自己转成apng保持透明。

**Comment by bddbnet** [comment]
我又试了一下，zip下载的确实不是原图。
希望多图和动图自动建立起相应id文件夹，使用掩码的方式有点怪，也有点难。
感谢提供了这么好的下载工具
