### ISSUE TITLE
AJAX !!!!!!!!!!!

### ISSUE THREAD

**Issue by sakurayang** [Mapaler/PixivUserBatchDownload#13]
看图……
![sp170318_224855](https://cloud.githubusercontent.com/assets/11017232/24073159/fbad8540-0c2d-11e7-94c2-b5490a2af35f.png)

无论如何就是AJAX错误……

**Comment by Mapaler** [comment]
按F12打开控制台看看错误输出呢？
不过多半是你Chrome没有使用Tampermonkey插件，直接安装的或者使用其他功能不够的插件，导致缺失能够跨域访问的高级扩展功能（GM_xmlhttpRequest函数）。
解决办法就是安装Tampermonkey插件，然后用插件来安装脚本。
