### ISSUE TITLE
按分数过滤这功能求实现

### ISSUE THREAD

**Issue by k316447978** [Mapaler/PixivUserBatchDownload#14]
我看了作者的 json 示例，也没找到分数的项呀，
如果可以，希望实现分别按分数过滤下载和 Tag 过滤下载这两个功能。
拜托大大。

**Comment by Mapaler** [comment]
因为我的理念比较忠诚于品牌，所以就是喜欢一个画师就把这个画师的所有作品下载下来。所以我主要设计的是按作者下载，目前暂没时间继续开发，就算要开发也是优先做多画师批量下载（储存喜欢的画师id方便自动更新）。其他搜索的JSON返回请参考[pixivpy](https://github.com/upbit/pixivpy)的wiki，需要看6.x API，你可以先看看有没有什么可以实现你想要的功能的API。
