### ISSUE TITLE
使用自定义函数之后下载某些标签当中含有符号的图片失败

### ISSUE THREAD

**Issue by wym3253** [Mapaler/PixivUserBatchDownload#16]
在掩码当中使用%{illust.tags.map(function(t)\{return t.name;\}).join(",")}之后，下载标签当中如果含有“:”的图片下载就会出错
如：
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=57687405
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=56647942
下载截图：
<img src="https://i.imgbox.com/Ny5lzEwc.png">

**Comment by Mapaler** [comment]
那应该就是有windows不支持的字符，我目前没时间改，你可以把结果用[replace方法](http://www.w3school.com.cn/jsref/jsref_replace.asp)替换一下“:”字符

**Comment by Mapaler** [comment]
%{illust.tags.map(function(t){return t.name;}).join(",").replace(/:/g,"_")},，把“:”替换成“_”。

**Comment by wym3253** [comment]
谢谢，问题已经解决。

**Comment by Mapaler** [comment]
之前因为和下载目录用的同一套函数，下载目录盘符会有一个“:”，所以只替换了保存路径里面的其他不支持字符，没有替换掉“:”。

我刚才更新了程序，保存路径里面会替换“:”到"_"，下载目录不会。
