### ISSUE TITLE
不变的作者名称bug

### ISSUE THREAD

**Issue by wym3253** [Mapaler/PixivUserBatchDownload#17]
下载[id212801_Anmi＠コミ1【あ02b】](https://www.pixiv.net/member.php?id=212801)时使用
id%{illust.user.id}_%{illust.user.name.split("@")[0]}%{多图或动图}/%{illust.filename}%{page}-%{illust.tags.map(function(t)\{return t.name;\}).join(",").replace(/:/g,"")}.%{illust.extention}
并没有自动去掉@符号
但是如[miazi @お仕事募集中](https://www.pixiv.net/member.php?id=2551745)等其它名字含有@符号的正常工作

**Comment by Mapaler** [comment]
因为他用的是全角的“＠”符号，Unicode no.65312，而不是半角的“@”符号，Unicode no.64。换个字体就能看出来了。

![image 1](https://user-images.githubusercontent.com/6565860/27122894-b05b3106-511e-11e7-8ff5-7387b8d248bf.png)

**Comment by wym3253** [comment]
嗯，开完issue之后就想到了，谢谢
