### ISSUE TITLE
我弄不明白，求解答其他下载不了，

### ISSUE THREAD

**Issue by luyang0506** [Mapaler/PixivUserBatchDownload#18]
![qq 20170811163640](https://user-images.githubusercontent.com/30741716/29206204-68f04528-7eb3-11e7-9424-645869ba1d8b.png)

**Comment by Mapaler** [comment]
你这样我也不明白啊，你需要告诉我你的掩码登详细设置、下载的页面，我看看能不能给你解决什么问题。
另外你试试更换保存路径，转http，以及简单掩码试试，用控制变量法排查问题。
还可以看看具体的错误代码是什么，类似下面这样。
![image 2](https://user-images.githubusercontent.com/6565860/29221891-035ddbae-7ef3-11e7-93c1-7452107dc37f.png)

**Comment by Mapaler** [comment]
另外我仔细看了下，你的下载列表里有相同的文件名，是不是相同文件名的文件已经存在了所以才不继续下载的？

**Comment by luyang0506** [comment]
@Mapaler 
![qq 20170812120842](https://user-images.githubusercontent.com/30741716/29237797-7ac79f8a-7f58-11e7-9497-d370847c7d20.png)

**Comment by Mapaler** [comment]
感觉是你的Aria2设置没搞好啊，是不是没有添加continue选项？如果添加了，你不把掩码发给我看我也不确定，很可能是你的掩码导致会有不同的文件下到同一个名字上去，然而不同的文件尺寸都不一样，于是发生了下载错误。
你目前的文件名很容易会产生不同画作保存的文件名却一样的情况。

**Comment by luyang0506** [comment]
恩，continue选项是什么，没添加的，
![1](https://user-images.githubusercontent.com/30741716/29238061-22833652-7f5f-11e7-8886-bcefc6f61ab3.png)

**Comment by Mapaler** [comment]
你复制给我不行啊，你那么长一串文本框只有这么的点鬼才知道你打的啥

**Comment by luyang0506** [comment]
%{illust.user.name}/[pixiv_ID=%{illust.user.id}_%{illust.user.name}]%{illust.title}%{new Date(illust.create_date).getFullYear()}年-%{new Date(illust.create_date).getMonth()+1}月-%{new Date(illust.create_date).getDate()}_p%{page}.%{illust.extention}
是pixiv_ID=作者id+插画原文件文件名+作品发布时间，
需要不需要远程我弄行的吗？

**Comment by Mapaler** [comment]
我和老婆出来约会了忘了，之前在家简单测试了下，应该就是我说的文件名重复的问题，你只能改掩码了。

**Comment by Mapaler** [comment]
两个简单办法，1、掩码内加入作品id，2、作品时间详细到秒

**Comment by luyang0506** [comment]
2、作品时间详细到秒                   %{Date.getMinutes()}-%{Date.getSeconds()}-%{Date.getMilliseconds()}对不对？
帮我改这个时间掩码

**Comment by luyang0506** [comment]
没事儿，那你和你老婆约会开心就行，我不打扰你们，我等你来帮我这样的，刚才发不对的，

- 作品时间详细掩码是{dt.getHours()}:%{dt.getMinutes()}:%{dt.getSeconds()}:%{dt.getMilliseconds()}对不对？

**Comment by Mapaler** [comment]
作品id就是`%{illust.id}`
时间的话，你之前的写法是每次都要创建一个新的时间对象写多了就很复杂
你可以先用`%{var dt=new Date(illust.create_date)}`创建一个名字为dt的时间对象，把作品创建时间放进去，然后后面就写`dt`就等于前面的`new Date(illust.create_date)`的值。
Windows文件名内不可以用`:`，你只能换其他字符。
比如可以写成
`%{var dt=new Date(illust.create_date)}%{dt.getFullYear()}年-%{dt.getMonth()+1}月-%{dt.getDate()}日 %{dt.getHours()}时-%{dt.getMinutes()}分-%{dt.getSeconds()}秒`
毫秒拿来没意义，因为P站系统就没存进去。

**Comment by luyang0506** [comment]
我发现一个问题的，请你看截图怎么样的。
![qq 20170813145120](https://user-images.githubusercontent.com/30741716/29247617-130f0160-803b-11e7-9303-da1d7eba6fa8.jpg)

**Comment by Mapaler** [comment]
你保存的文件名前面有空格，然而Windows下文件名不能以空格开头。

**Comment by luyang0506** [comment]
原来，您有办法吗？空格开头都除去了，可以保存的文件名。

**Comment by Mapaler** [comment]
为什么你这里面会有空格？

**Comment by luyang0506** [comment]
我真不知道的，你看掩码怎么没有空格的。
保存路径：%{illust.user.name}/[pixiv_ID=%{illust.user.id}_%{illust.user.name}]%{illust.title}%{var dt=new Date(illust.create_date)}%{dt.getFullYear()}-%{dt.getMonth()+1}-%{dt.getDate()}-%{dt.getHours()}-%{dt.getMinutes()}-%{dt.getSeconds()}_%{page}.%{illust.extention}
文件输出模式格式：%{illust.url_without_page}%{page}.%{illust.extention}

**Comment by Mapaler** [comment]
![image 1](https://user-images.githubusercontent.com/6565860/29259190-37ca19be-80f3-11e7-91ec-5f2e15c22fe3.png)
问题出在他的作品的标题名里有斜杠，遇到斜杠就会多一建层文件夹，恰好斜杠两边又是空格，于是建立文件失败。

解决办法，把标题里的斜杠替换成其他字符
`%{illust.title}`>>`%{illust.title.replace(/[\/\\]/ig, "_")}`
详见 [掩码#批量替换字符串](https://github.com/Mapaler/PixivUserBatchDownload/wiki/%E6%8E%A9%E7%A0%81#%E6%89%B9%E9%87%8F%E6%9B%BF%E6%8D%A2%E5%AD%97%E7%AC%A6%E4%B8%B2)

**Comment by luyang0506** [comment]
感谢你很厉害的，我新手不会的，有点不懂看掩码的。
