### ISSUE TITLE
最近的更新出现的问题

### ISSUE THREAD

**Issue by river1** [Mapaler/PixivUserBatchDownload#2]
会反复加入已添加过的下载
[这个](https://github.com/Mapaler/PixivUserBatchDownload/tree/85e331c1cdfeba0a5829723460559a12620daa6a)是最后能用的版本

**Comment by Mapaler** [comment]
什么是“反复加入已添加过的下载”？你是不是选成快速模式去了，那是因为没有获取扩展名，因此每个图片需要添加3种可能。

还是说和以前下载的路径不一样了？那是因为以前没考虑到一些特殊情况，没有对某些特殊字符进行处理，新的对特殊字符进行了处理，导致和以前路径不一样。为了将来使用不会出现无法下载的情况，还是请使用新版吧。

另外目前的掩码里含有作者名，但是作者名是可以随时改的（很多人每次例大祭都会改），导致文件夹不一样。因此新版推出了一个“user_pixiv_id”掩码，虽然不像昵称一样容易辨识但这个账户是无法改变的，可以手动将“user_name”修改为“user_pixiv_id”以达到用户文件夹的唯一（为了延续老版没有改为默认掩码）。如果不需要文件夹名显示昵称，去掉这个掩码用纯数字名就可以保证万无一失了。

**Comment by river1** [comment]
抱歉，没有写清楚，log里面是这样的
2016-04-05 10:12:33.249736 [ERROR] [AbstractCommand.cc:345] CUID#103 - Download aborted. URI=http://i1.pixiv.net/img-original/img/2013/01/21/14/46/10/33007456_p0.jpg
Exception: [AbstractCommand.cc:345] errorCode=22 URI=http://i1.pixiv.net/img-original/img/2013/01/21/14/46/10/33007456_p0.jpg
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403
链接看不出来有什么问题，但是返回了403
我再仔细测试一下

**Comment by river1** [comment]
referer变成了这个
/member_illust.php?id=xxxxxxxxx

**Comment by river1** [comment]
referer变成了这个
/member_illust.php?id=xxxxxxxxx

**Comment by river1** [comment]
referer变成了这个
/member_illust.php?id=xxxxxxxxx

**Comment by river1** [comment]
referer变成了这个
/member_illust.php?id=xxxxxxxxx

**Comment by river1** [comment]
referer变成了这个
/member_illust.php?id=xxxxxxxxx

**Comment by Mapaler** [comment]
403应该是referer不对。
%{page}修复了，其他问题我这里并没发现。
Safari不是好多年都没更新了么，不支持HTML5很正常。
Chrome请用最新版脚本，并重置一下脚本的设置看看。但是我还是在火狐上写和测试，目前只给Chrome写了一个兼容点，其他的都能用。

**Comment by river1** [comment]
Referer这个可以在设置里面修改吗
我把%{url}改成其他的，发现不能保存

**Comment by Mapaler** [comment]
我修复了，之前光注意修改怎么让没有设置的添加设置了，忘记写保存设置这一段了。
哪些Referer可以用可以自己测试，不懂的话就用我默认的。

**Comment by river1** [comment]
OK, 能用了
