### ISSUE TITLE
errNum=13 errorCode=18 无法下载，请求帮助

### ISSUE THREAD

**Issue by xyby01** [Mapaler/PixivUserBatchDownload#20]
创建任务正常，但是在下载过程中出错，所有图片全部失败。win10系统，控制台代码如下：
08/19 21:00:48 [NOTICE] Download GID#59bfbfa43640c0a9 not complete: D:/PixivDownload//53872504_p0.jpg

08/19 21:00:48 [ERROR] CUID#27 - Download aborted. URI=https://i.pximg.net/img-original/img/2015/12/04/09/27/45/53872482_p0.jpg
Exception: [AbstractCommand.cc:403] errorCode=18 URI=https://i.pximg.net/img-original/img/2015/12/04/09/27/45/53872482_p0.jpg
  -> [RequestGroup.cc:760] errorCode=18 Download aborted.
  -> [util.cc:1597] errNum=13 errorCode=18 Failed to make the directory D:/PixivDownload/, cause: Permission denied

新手，不知所措，还请帮助

**Comment by Mapaler** [comment]
重点是 Failed to make the directory D:/PixivDownload/, cause: Permission denied
就是无法创建D:/PixivDownload/这个文件夹，权限不够，你需要自己换一个有权限使用的下载目录。

**Comment by xyby01** [comment]
好的感谢，才发现默认的D盘……我只有一个C盘（笑出声）顺便提问，是不是删除aria2文件夹下的aria2_Pixiv.session.txt即可删除下载记录，从而避免已下载文件被删除后重复下载的问题？

**Comment by Mapaler** [comment]
aria2_Pixiv.session.txt记录的只是当前的下载回话，用于你关了Aria2，下次还打开可以继续下载。下载成功的回话是会从这里面删除的。你看我的Aria2配置，里面有断点续传、不改名、跳过相同文件，所以是不会重复下载同一个文件的。（但是如果掩码设置不好，发生了不同文件下载到同一个文件名就会发生错误，如：#18）
