### ISSUE TITLE
可以登陆，但是下载时会AJAX发送失败

### ISSUE THREAD

**Issue by Jsffyayoi** [Mapaler/PixivUserBatchDownload#22]
之前都能正常使用，在关机重启之后就出现
![qq 20171109231316](https://user-images.githubusercontent.com/33521701/32612743-00a57942-c5a4-11e7-8f13-29d23deb4d86.png)
希望能告知解决方法，谢谢

**Comment by Mapaler** [comment]
试试如下两个网址是否能直接访问。
https://app-api.pixiv.net/
https://oauth.secure.pixiv.net/auth/token
不能访问就请检查hosts，说明主页里面有写。

**Comment by Jsffyayoi** [comment]
今天重新启动已经解决了。谢谢。
另外这两个网址不论我是否加入hosts之后都是显示
{"error":{"user_message":"\u60a8\u6240\u6307\u5b9a\u7684\u7aef\u70b9\u4e0d\u5b58\u5728","message":"","reason":"","user_message_details":{}}}

{"has_error":true,"errors":{"system":{"message":"404 Not Found","code":null}}}

**Comment by Mapaler** [comment]
对的，只是看有没有返回内容，不管返回的是什么（因为并没有提交请求）。如果是显示服务器无法连接就有问题了。

**Comment by Jsffyayoi** [comment]
好的，谢谢。
