### ISSUE TITLE
关于火狐57 + 油猴4.0程序运行失效问题

### ISSUE THREAD

**Issue by xyby01** [Mapaler/PixivUserBatchDownload#23]
在11月份的时候，大概是stylish进行了一次更新，导致访问P站时的蓝色按钮不再出现了（但问题也许出在firefox的更新或者是P站网页版的更新，我不是很清楚），现在在stylish的管理样式中查看代码，发现14处错误，不知道如何修改，请求作者更新一下，感谢。

**Comment by Mapaler** [comment]
你有没有试着重新安装一下样式？我有注意Stylish的更新，更新后清空了所有的样式，重新去发布的页面上点安装后仍然正常使用的。

**Comment by Mapaler** [comment]
那14个不是错误，只是警告，有一堆是它不认识的CSS属性，但是浏览器可以识别。
还有一堆是说没有具体内容的空规则，我调试过程中残留的，也不影响。

**Comment by xyby01** [comment]
感谢，个人重装了Firefox至56，并重新安装stylish和tempermonkey，终于好用了（所以并不知道问题具体出在哪里），但至少好用了。

**Comment by Mapaler** [comment]
你可以用56或者52 ESR，52 ESR是最后支持各种第三方NAPI插件的版本，56是最后支持Flash和传统扩展的版本。57火狐把自己的根（扩展）都给断掉了，不敢升级。

**Comment by Mapaler** [comment]
我去试了，是油猴4.0还不完善，有bug。我暂时没时间去调试，可以用Tampermonkey扩展，或者留在56。

**Comment by Mapaler** [comment]
取消对油猴4.0的支持，后续以Tampermonkey为开发平台
