### ISSUE TITLE
关于提示“这幅作品已经被删除了”而不能下载的问题

### ISSUE THREAD

**Issue by MichaelMai2000** [Mapaler/PixivUserBatchDownload#25]
我在下载画师[320664 - 黒澤ユリ](https://www.pixiv.net/member.php?id=320664)的时候遇到了很多下载出错的问题。回溯出错的链接，竟然发现图片被删除（“这幅作品已经被删除了”），然而链接还能被获取到！感觉非常神奇。同样的情况对于其他画师应该也有，请问这是bug吗？

**Comment by MichaelMai2000** [comment]
类似的还有这一张图[59717746](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=59717746)

**Comment by Mapaler** [comment]
我是用的手机API直接获取的列表返回的json，除了添加几个特殊字符串，基本没改动，你可以看看是不是这些被删除的图片有特殊的属性值来定义。我写程序的时候没有遇到过这种情况，今天上班了特别忙暂时帮不了你。

**Comment by Mapaler** [comment]
如果找到了删除的定义，那么你可以把这个定义加一个掩码导向一个不存在的地址就不会被保存了，不过Aira2还是会报错。
其实是想过加一个过滤功能的，但是暂时没时间。

**Comment by Mapaler** [comment]
我刚才试了一下，你发的黒澤ユリ并没有产生错误，全部下载下来了，59717746我也看不到

**Comment by MichaelMai2000** [comment]
可是我抓取到了啊，对于黒澤ユリ，你能抓到59717746这一张图吗？。。。

**Comment by Mapaler** [comment]
那就这样吧，应该是P站服务器返回的问题
