### ISSUE TITLE
特殊字符文件名导致的aria2意外错误

### ISSUE THREAD

**Issue by MichaelMai2000** [Mapaler/PixivUserBatchDownload#26]
[57394283](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=57394283)的图片标题，里面好像有全角空格？？？没检查出来到底是什么问题。
[58103496](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=58103496)的图片标题，有个方框，不知道是什么东西，也报错了。

**Comment by Mapaler** [comment]
你可以用掩码替换掉这些特殊字符啊。

差错的话，可以在webui里手动添加连接试试，注意修改out参数为你要保存的文件名（文件名掩码的完整输出结果），查查看哪些字符导致的。

**Comment by MichaelMai2000** [comment]
@Mapaler 
 在notepad++里面UTF-8 无BOM显示 BS
上面这个好像真的没法办，应该直接去aria2里面删了。

**Comment by Mapaler** [comment]
![image 3](https://user-images.githubusercontent.com/6565860/36644379-660a7b58-1a94-11e8-9e3f-a05ef8042f69.jpg)
58103496的标题，特殊字符是U+0008，对应的是'BACKSPACE'，这都已经不是特殊字符而是是不应该出现的控制字符了，CMD里的消息也应证了是退格
![image 4](https://user-images.githubusercontent.com/6565860/36644399-d5bdc086-1a94-11e8-92bf-0e62d49bb426.png)
可以用这样来表示指定Unicode编号的字符
![image 5](https://user-images.githubusercontent.com/6565860/36644418-2d159d86-1a95-11e8-8434-91c06c5ad45d.png)
![image 6](https://user-images.githubusercontent.com/6565860/36644426-5977ab76-1a95-11e8-82de-3212cbe90f90.png)
<hr>
然后是 57394283

![image 8](https://user-images.githubusercontent.com/6565860/36644528-b72ce7e4-1a96-11e8-8d39-e06df5bc7c50.png)

20就是空格（10进制是32），问题出在9，9对应的是'CHARACTER TABULATION'，制表符，就是按TAB添加的那个字符，也是不能出现在文件名的。

**Comment by Mapaler** [comment]
P站怎么会让这些特殊字符进入标题的，真是奇怪

**Comment by MichaelMai2000** [comment]
已解决。p站好迷啊。

**Comment by Mapaler** [comment]
正常情况下这些字符都无法输入的，不知道为什么会出现啊。
https://en.wikibooks.org/wiki/Unicode/Character_reference/0000-0FFF
控制字符有一大堆啊，我也不知道哪些是可以用的，哪些是不可以用的。

**Comment by MichaelMai2000** [comment]
那我只能慢慢积累经验了2333333

**Comment by Mapaler** [comment]
只要有人给个哪些控制字符是可以用的，我就好添加了。

**Comment by Mapaler** [comment]
我刚才把 \u0000-\u001F \u007F-\u00A0 都添加进了自动替换的字符，顺便改了其他一些东西，你用用看新版有没有什么bug。

**Comment by MichaelMai2000** [comment]
好的，我更新一下。最近应该不会大量下载图片了，不过多谢了！
