### ISSUE TITLE
请问可否实现批量导出下载链接，自己用其他工具下载的功能

### ISSUE THREAD

**Issue by OHLIA** [Mapaler/PixivUserBatchDownload#27]
问题表达的不清，
是直接导出到远程服务器上的的Aria2里下载。
是因为cookies吗？

**Comment by Mapaler** [comment]
支持发送到远程Aria2服务器下载啊，填写远程服务器的JSON-RPC地址就可以。
需要导出下载链接，就用文本模式即可。

**Comment by OHLIA** [comment]
我刚才尝试推送到远程rpc，但是全都无法下载

**Comment by Mapaler** [comment]
首先你确定远程JSON-RPC地址配置正确，能够检查到版本号。

token和cookies都不会发送到远程的，因为目前下载是不需要的，你可以试试webui直接远程管理添加单个图片地址看看能不能下载。

你勾一下“图片网址https转http”再下载试试，如果能下载了那就试远程的没有设置证书导致的，可以在远程Aria2启动参数里添加“check-certificate=false”，取消证书检查就能下载https的了。

**Comment by OHLIA** [comment]
我想了下，连接远程的aria2是有设置密码的，
但是你的用户样式设置里面只要求写RPC地址，没有密码选项，
是否跟这个有关呢？

**Comment by Mapaler** [comment]
有啊，你没看完“远程下载”里面的说明吗，有token的格式写法。
如果还是用的老的用户名密码模式，把token改成用户名就行。

**Comment by OHLIA** [comment]
一直用ariang，
都忘了有这样的写法，
是我大意了。

**Comment by Mapaler** [comment]
这是源自ThunderExport和YAAW的写法，不是原生的，但是我觉得更好用，一条字符串就记录了几种不同格式方便储存，而且和ftp的帐号密码格式一样很容易理解。

**Comment by Mapaler** [comment]
那么你后来成功了没有啊？

**Comment by OHLIA** [comment]
可以了，我想问下，能实现，下载时候图片用P站上的名称吗？

**Comment by Mapaler** [comment]
当然可以，用掩码。

**Comment by OHLIA** [comment]
最近stylish被发现会上传用户所有浏览历史╰（‵□′）╯。

**Comment by Mapaler** [comment]
Stylish不是早就有问题了么，我也很早就把Wiki里面的推荐扩展改成了Stylus

**Comment by Waitung** [comment]
Stylus在https://userstyles.org不好安装样式，期望能在http://freestyler.ws也发布

**Comment by Mapaler** [comment]
@Waitung 不属于本issue的主题。
而且安装样式有什么麻烦的，就算不能直接安装，复制粘贴也行啊。
