### ISSUE TITLE
输出文本下载，动图变成一张张jpg

### ISSUE THREAD

**Issue by OHLIA** [Mapaler/PixivUserBatchDownload#28]
输出文本下载，
动图变成一张张jpg，有点奇怪。。。

**Comment by Mapaler** [comment]
因为我是获取的动图原始文件，如果是上传的透明png，这里获取到的就是可以透明的png。你获取到jpg说明作者传的就是jpg。

**Comment by OHLIA** [comment]
那看来要自己合成回去。。。

**Comment by Mapaler** [comment]
你以为P站网站上是真的动图格式吗？其实P站网站查看动图是下载的一个包含一堆jpg的压缩包，解压后由程序一张一张画到网页上，也不是单个动图文件的。

**Comment by OHLIA** [comment]
受教了，之前一直以为是gif

**Comment by Mapaler** [comment]
而且那个压缩包里是已经二压的图片，传的透明png也会变成jpg，而我程序会获取到原始透明png图片，你可以转成apng。

**Comment by Mapaler** [comment]
P站可以传单个gif文件的，这样就是图像自己本身动，不用程序来画。下载下来也是单个gif。但是gif限定只有256色，看图全是马赛克或者色块，所以现在画师都不怎么用它了。

**Comment by lgq1349422030** [comment]
疑惑，我通过这个方法

![image](https://user-images.githubusercontent.com/57399652/77982449-f55e8380-733e-11ea-897e-34bdd18d87c4.png)


得到的居然是png图片，而用插件和仙尊下载的都是jpg？

**Comment by Mapaler** [comment]
@lgq1349422030 因为作者上传的原图是png，仙尊下的是P站二压后的zip包。

**Comment by Mapaler** [comment]
@lgq1349422030 之前理解错了，你是说另存为的图片是png吧？
那是个cavans，HTML5的画布，p站按时间顺序把zip里的jpg一张张画到这个画布上形成了动画。
对于浏览器来说那已经是一张新画的图片了，不是原来的jpg了，所以保存出来的是当时那个瞬间的无损png格式。
