### ISSUE TITLE
v3.0开发讨论

### ISSUE THREAD

**Issue by Mapaler** [Mapaler/PixivUserBatchDownload#3]
@river1 因为作者名称都是假名辨识度不高，而且还经常参CM而改名，导致下载路径改变。之前就在考虑将默认下载文件夹改为纯id数字，利用desktop.ini来显示Unicode名称。有很多解决方案，php很简单但是怕我的免费服务器承受不起研究了JS生成UTF-16文本的办法。今天又找到了一个纯JS将图片转为ico的库，可以再减少一个jpg转ico的程序。[Javascript Favicon Creator](http://mrcoles.com/favicon-creator/)
利用Aria2的种子下载可以将二进制数据发送下载，只不过得到的都是torrent扩展名，之后再用一个VBS将文件还原为正常状态并且应用上去，得到下图这种结果。但缺点是只有Windows下才支持。
用户需要做的就是每次下载后运行一次VBS，你觉得这个功能如何。

![image 4](https://cloud.githubusercontent.com/assets/6565860/14341973/d15423dc-fcc8-11e5-9954-214b904aee38.jpg)

![image 5](https://cloud.githubusercontent.com/assets/6565860/14341974/d15b1ac0-fcc8-11e5-8984-564568bf68f4.jpg)
文件夹下将会多这两个文件
![image 6](https://cloud.githubusercontent.com/assets/6565860/14341975/d15ba4cc-fcc8-11e5-87cb-a9c9dc5407cb.jpg)

**Comment by river1** [comment]
这个功能好复杂，我觉得如果用js生成ico的话，文件已经在本地了，硬塞给Aria2，不如直接给浏览器下载好了。

**Comment by Mapaler** [comment]
刚刚找到了不用GM_xmlhttpRequest也能获取到单页漫画的扩展名的方法了。

**Comment by Mapaler** [comment]
JS生成的文件是无法自动保存到本地的，必须手动操作才行，可是一个一个手动操作太麻烦了，所以利用Aria2有限的二进制发送功能把ini和ico保存到文件夹，再批量对所有文件夹内的改名不快一些么。

**Comment by Mapaler** [comment]
擦，因为跨域问题无法在浏览器中获取图片的内容，也就没法在浏览器里生成ico，各种代码都搞好了才不能用。
看来只能先用aria2保存图片到本地了。
![image 1](https://cloud.githubusercontent.com/assets/6565860/14489548/71f0210c-01a0-11e6-8818-582702d323cb.jpg)

**Comment by Mapaler** [comment]
@river1 来试试更改文件名和图标的新功能吧
https://github.com/Mapaler/PixivUserBatchDownload/tree/develop

**Comment by river1** [comment]
试了一下vbs运行到正在转换就自己关闭了，然后并没有转换，手动转了之后有效果

**Comment by Mapaler** [comment]
因为我之前没有在最后弹出确认对话框，完成后会直接结束，现在为了Debug，我把完成对话框给改成了弹出方式。如果没有出现就说明运行没成功。
毕竟不知道系统刷新图标缓存是怎么的机制，只能现在这样了。
Desktp.ini就是Windows Explorer才支持的。

**Comment by Mapaler** [comment]
研究过程中居然发现有很多作品都被删除了，怎么回事
