### ISSUE TITLE
请问哪里更改默认的命名方式？

### ISSUE THREAD

**Issue by kouyoukurotsuki** [Mapaler/PixivUserBatchDownload#31]
请问默认的“illust.filename”输出自动加了_p字样，如何去掉？

**Comment by Mapaler** [comment]
看你希望用什么了，原始文件名里就是这样的，p表示page的意思。
`%{illust.filename}` 相当于 `%{illust.id}_p`
你不需要自己用其他的代替啊。

**Comment by kouyoukurotsuki** [comment]
OK,解决了，因为想和之前用的下载器同一个命名格式所以想试着自己改一下，感谢回复
