### ISSUE TITLE
别人收藏太多提示错误信息:Rate Limit

### ISSUE THREAD

**Issue by aa231410** [Mapaler/PixivUserBatchDownload#32]
一直到提示错误信息的时候获取到的下载链接在哪里可以提取到

**Comment by Mapaler** [comment]
你把具体页面给我看看

**Comment by aa231410** [comment]
https://www.pixiv.net/member.php?id=959849你可以获取下收藏试试看

**Comment by aa231410** [comment]
![_20180830121534](https://user-images.githubusercontent.com/42795691/44829275-75e26d00-ac4e-11e8-89c6-6fd04b1b5afc.jpg)
![_20180830121543](https://user-images.githubusercontent.com/42795691/44829276-75e26d00-ac4e-11e8-9fa6-acd780d8edc6.jpg)
出错之后就不能下载了，得重新获取，但是网站好像有限制不能获取这么多
有没有什么办法吧已经获取到的，或者获取到一半暂停的那部分给发送到aria2让它下载么

**Comment by Mapaler** [comment]
* 首先，这个Rate Limit出现原因不是程序BUG，而是P站认为你访问过快而临时的封禁，我这边就正常的全部获取了。也许是你的网络很好，浏览器处理也很快导致的。  
  ![screenshot 2018-08-30 15 32 18](https://user-images.githubusercontent.com/6565860/44836586-ecd92f00-ac69-11e8-84ff-f8147c37fc4d.png)
* 其次，出现上述错误情况后，你可以尝试再次点击收藏进行断点续传分析。
* 刚才我也更新了一下程序，使其在中断或者发生错误时，可以操作当前已获得数据。
