### ISSUE TITLE
P站改新版了，作者页面找不到PUBD了

### ISSUE THREAD

**Issue by k316447978** [Mapaler/PixivUserBatchDownload#35]
是因为PUBD的样式没有更新的原因吗？
还是因为我个人的原因？按钮找不到了。

**Comment by Mapaler** [comment]
你好，刚才测试是有的，PUBD最新版是v5.4.30。你看你的PUBD是否安装了最新版。

**Comment by k316447978** [comment]
抱歉，我的P站界面自动切换到新版了
我也找不到切换回旧版的按钮，不知道作者大大是否有考虑过为新版适配样式呢？


![2018-09-18t03-11-28 588z](https://user-images.githubusercontent.com/8279143/45662340-1502d200-bb34-11e8-8524-c211b4d0ea46.jpg)

**Comment by k316447978** [comment]
作品详情页正常显示了，之前竟然没留意到右上角......
一直都是直接拉下来看标题下的作者信息的，非常感谢大佬的耐心解答

**Comment by Mapaler** [comment]
新版作者改到了右上角，我为了让人好找，所以还是放在作者头像下面啊。

**Comment by Mapaler** [comment]
新版左上角也有头像吗？

**Comment by Mapaler** [comment]
以前的头像是在左上角，所以新版的改版对应的应该是右上角的那个，而不是下面的那个。
我的思维是，左边找不到，就先找右边，之后才考虑其他方向。

**Comment by Mapaler** [comment]
总之找到了能用就好，现在P站完全被墙了，只能用代理上网也是个麻烦了。

**Comment by k316447978** [comment]
的确，能用就好，感谢大佬
