### ISSUE TITLE
我看P站更新了，好像改HOSTS也不能进入了，挂梯子进去看了看发现界面也变了，咱们的工具估计什么时候可以更新呢？

### ISSUE THREAD

**Issue by aa231410** [Mapaler/PixivUserBatchDownload#36]
我看P站更新了，好像改HOSTS也不能进入了，挂梯子进去看了看发现界面也变了，咱们的工具估计什么时候可以更新呢？

**Comment by ToyamaNao** [comment]
![qq 20181005222704](https://user-images.githubusercontent.com/31986578/46541193-e46db700-c8ed-11e8-915d-cd6918db0270.jpg)
现在打开P站之后UI界面可能是无法显示PUBD了？或者说还是我没找到。。。

**Comment by Mapaler** [comment]
去具体的作品页面看右上角作者头像下面

**Comment by ToyamaNao** [comment]
> 去具体的作品页面看右上角作者头像下面

好的谢谢，那请问下，是不是新UI下不能像以前那样实现在作者首页就进行抓取了

**Comment by Mapaler** [comment]
不是，是因为之前我的账号登录作者页面还是老的UI，所以没法做，作品页面是新UI所以做了。
这几天国庆出去玩没电脑我也没办法去看现在的UI是怎样。

**Comment by Mapaler** [comment]
已经更新了

**Comment by ToyamaNao** [comment]
> 已经更新了

好的已经看到的，谢谢作者了~
