### ISSUE TITLE
建议加个新功能

### ISSUE THREAD

**Issue by luochris** [Mapaler/PixivUserBatchDownload#39]
你这个插件很不错啊，要是能加个新功能就好了~，就是能下载当前作品业的内容， 我在你的基础上自己改了改加了这个功能，但是你要是更新了我又得改...

**Comment by Mapaler** [comment]
不是很明白意思啊，只下载当前作品吗？

我现在正在dev5分支开发新版本，代码变了很多，所以还在测试，多半你又得改。
https://github.com/Mapaler/PixivUserBatchDownload/pull/37

**Comment by luochris** [comment]
有几个建议我统一说一下：
1、开始按钮不需要下拉菜单，因为选项并不需要经常用，点开始按钮就打开主窗口比较好，现在这里多了一次无用的点击。
2、选项按钮加到入到主窗口的标题栏按钮里，和关闭放在一起就好。
3、在作品页，可以单独下载当前页的作品。在那个单选框加个”当前作品“，点击只下载当前面的作品。
4、这3个窗口建议改成position: fixed; 比较好，有时候拖到下面时点击开始按钮，发现窗口弹在上面，要拉上去。
5、点击开始按钮打开主窗口时调一次获取用户信息这样体验比较好，这个不是太重要哈，感觉好点。

上面这几个功能我都改出来了，就是到时你一更新就比较麻烦，所以说一下，你参考参考~

6、最好能实现动图生成gif。
7、作品页底部的”相关作品“下载功能，也可以考虑下，是不是可以做。

**Comment by Mapaler** [comment]
1、我曾经考虑过，但是当时有考虑主按钮做多人下载收藏按钮，需要重构结构，所以就搁置下来，不过目前没有经历和技术开发多人，可以考虑像你说的这样做，但是目前主要任务是解决5.7版本bug，改ui需要隔一段时间。
2、我需要保留菜单，其实以前计划有其他功能，不过没时间做。可能会考虑添加选择主按钮功能设置。
3、当前作品我设定为另一个功能按钮，因为获取的API不一样。
4、我故意设定为absolute，因为我希望页面随网页而动，不影响查看页面其他部分，另外设置窗口大了后，fix显示不完。至于位置问题你试试5.7，我已经把窗口打开时的初始位置设置在当前视觉范围内。
5、不懂，你设置里直接勾上自动获取信息不就好了吗？
6、Aria2无法从本地传输下载以外的其他数据，该功能实现需要另外写程序，但是我对py和node还是java都不会。另外我会优先考虑apng。
7、目前专做按作者下载，其他不考虑。PUBD使用手机APP的API来获取信息，其实和网页是无关的（只传输一个作者id到API），也就是说甚至P站不能打开，直接在PUBD里输入用户id也能下（不过我没这么做）。就算要获取相关作品的内容，其本来就是随机的，手机获取的和你在电脑上看到的其实已经不同了。

**Comment by luochris** [comment]
明白你的意思了。
还有个问题不知道你发现了没有，检查插入点创建开始按钮，有点不稳定，有些页面创建后会突然消失，看不到开始按钮了，刷新页面又会出来。 你这个代码封闭得太厉害，我是看了蛮久才基本看懂。UI框架封装得很不错，我想以后我写别的插件也可以用得上，呵呵。不知道方不方便加个Q啥的...

**Comment by Mapaler** [comment]
其实很多东西希望用 Object.create() 来写的，但是实在是学不来

**Comment by Mapaler** [comment]
你好，我在dev5分支开发了当前作品下载，你可以试试看，进去点raw查看原始数据来安装。
https://github.com/Mapaler/PixivUserBatchDownload/blob/dev5/PixivUserBatchDownload.user.js

这次有很多改动，是为了给将来做多画师下载做准备。
另外加入了对页面变动的支持，解决按钮总是消失的问题，以及更换页面后id没有修改的问题
