### ISSUE TITLE
部分作品获取不了下载链接

### ISSUE THREAD

**Issue by merry200603** [Mapaler/PixivUserBatchDownload#4]
部分作品获取不了下载链接
如该画师： http://www.pixiv.net/member_illust.php?id=703995

疑似部分作品链接异于常规，请核实下。

疑似问题作品：http://i3.pixiv.net/c/600x600/img-master/img/2014/11/11/17/37/17/47029738_p0_master1200.jpg

**Comment by Mapaler** [comment]
v2.5.0开始支持获取单页漫画的真是扩展名的，遇到单页漫画会在网页中生成对应的框架来获取。
![image 8](https://cloud.githubusercontent.com/assets/6565860/14732255/6fc1a102-088b-11e6-848c-54a6d3027f03.jpg)
我这里验证是可以使用的
![image 6](https://cloud.githubusercontent.com/assets/6565860/14732245/54efdfa6-088b-11e6-98e2-37e80d8d62ac.jpg)
如果你确保是最新版脚本，那么请检查你是不是修改了pixiv的refferer，如果修改了也会导致无法正常访问页面。

**Comment by merry200603** [comment]
我这边无论是2.6还是3.0.5会长时间停留在953/954界面，如下：
![2 6](https://cloud.githubusercontent.com/assets/2960864/14733505/080f45cc-0896-11e6-9c40-25f767e704ea.png)

刚才仔细看了下，好像是长时间卡在广告上了，等了一段时间后确实是可以的，多谢！

**Comment by Mapaler** [comment]
因为那个mode=big页面严格需求referer，所以必须从作品页面链入。而普通httpquest无法设置，一旦用GM_httpRequest则调试会很麻烦，还必须用扩展（之前可以手动执行代码）。所以就研究了两层框架地方法。
