### ISSUE TITLE
远程Aria2连接失败

### ISSUE THREAD

**Issue by MichaelMai2000** [Mapaler/PixivUserBatchDownload#41]
Chorme扩展中YAAW2可以成功远程连接。
直接拷贝YAAW2中成功的配置到插件，断开YAAW2，插件显示“Aria2连接失败”。
rpc链接中含有token。
控制台好像可能有反应了一些问题？附上截图
![image](https://user-images.githubusercontent.com/10582944/47965009-4c91f300-e07c-11e8-80c1-14d2943ce604.png)

**Comment by Mapaler** [comment]
是不是你第一次连接的时候弹出是否允许连接被你拒绝了？我能设定基本的localhost不弹出提醒，其他主机我没法一个一个设置。

**Comment by Mapaler** [comment]
![screenshot 2018-11-05 09 07 39](https://user-images.githubusercontent.com/6565860/47972767-4d597200-e0da-11e8-8c36-ae20e62bd9ec.png)
编辑脚本进设置看看是不是设置成了黑名单
