### ISSUE TITLE
登陆账号报错

### ISSUE THREAD

**Issue by e-onion** [Mapaler/PixivUserBatchDownload#42]
之前都能正常使用，最近就一直登陆报错
![m _y u21 hp u3hsl ge](https://user-images.githubusercontent.com/47427873/52769646-3c72b200-3074-11e9-84c5-9681e540827c.png)
错误代码：1508
access_denied
这该怎么弄

**Comment by Mapaler** [comment]
![screenshot 2019-02-14 16 30 04](https://user-images.githubusercontent.com/6565860/52773421-d850ed80-3075-11e9-99ec-c69fe29e7aeb.png)
我这边还是能正常登陆的。
你下个P站官方手机客户端来试试看，我调用的是手机APP的API，登陆信息应该一样的。
https://play.google.com/store/apps/details?id=jp.pxv.android

**Comment by e-onion** [comment]
重启了下浏览器又好了
