### ISSUE TITLE
SSL/TLS handshake failure error使用问题求助

### ISSUE THREAD

**Issue by KiramekiMamika** [Mapaler/PixivUserBatchDownload#43]
问题如下，不知是代理的问题还是其他问题，使用SSR与Clash，能下载一会，然后就会出现这个问题。
24号使用了一天没有问题，只是偶尔会停一下，马上就恢复了。25号就出现这个了且一直到任务失败都无法下载。
https://upload.cc/i1/2019/02/26/OKqLEf.png
感谢

**Comment by Mapaler** [comment]
i.pximg.net还没被墙吧，你可以不用对aria2使用代理的。只需要对pixiv.net代理就行。
另外你可以试试https转http

**Comment by KiramekiMamika** [comment]
感谢您的回答，HTTPS转HTTP后可以正常使用了。
还有个问题是我在给文件夹命名时使用
%{illust.user.name}%{illust.user.id}/%{illust.title}_p%{page}.%{illust.extention}
我想在用户ID两方加上一个[]，比如XXXXXXX[1111111]。
该如何操作？

**Comment by Mapaler** [comment]
```
 %{illust.user.name}[%{illust.user.id}]/%{illust.title}_p%{page}.%{illust.extention}
```

**Comment by Mapaler** [comment]
https的下载不了应该是你的ssh没装好，或者你的证书没更新。

**Comment by KiramekiMamika** [comment]
应该是证书的问题，感谢回答

**Comment by Mapaler** [comment]
另外我发觉你的掩码可能存在冲突，有的作者很多作品都叫“无题”，你这个会产生重名冲突。

**Comment by KiramekiMamika** [comment]
感谢你的提醒，我现在的掩码是
%{illust.user.name.replace(/[\\/\\\\]/ig, "_")}[%{illust.user.id}]/%{illust.filename}%{illust.title.replace(/[\\/\\\\]/ig, "_")}%{page}.%{illust.extention}
请问应该如何修改

**Comment by Mapaler** [comment]
`%{illust.user.name.replace(/[\\/\\\\]/ig, "_")}[%{illust.user.id}]/%{illust.id}-%{illust.title.replace(/[\\/\\\\]/ig, "_")}_%{page}.%{illust.extention}`
我建议这样吧

**Comment by KiramekiMamika** [comment]
好的，十分感谢您的帮助。

**Comment by KiramekiMamika** [comment]
大佬，又出现了个之前没出现的神必问题，请问是什么原因
[img]https://upload.cc/i1/2019/02/27/VKpOC0.png[/img]

**Comment by KiramekiMamika** [comment]
改掩码替换掉后可以了，不好意思打扰了

**Comment by Mapaler** [comment]
因为冒号吧
![文件名不能包含字符](https://raw.githubusercontent.com/wiki/Mapaler/PixivUserBatchDownload/images/filenameForbiddenChar.jpg)
