### ISSUE TITLE
建议更新pixiv的nginx反代访问方法QwQ

### ISSUE THREAD

**Issue by MoveCloudROY** [Mapaler/PixivUserBatchDownload#44]
[mashiro的blog](https://2heng.xin/2017/09/19/pixiv)

**Comment by Mapaler** [comment]
对不起，你发的那个网页顺序太乱了，我看不懂。
有涉及到需要修改PUBD程序的吗？

**Comment by MoveCloudROY** [comment]
不需要

**Comment by MoveCloudROY** [comment]
简单的说就是

1. 从[这里](https://github.com/mashirozx/Pixiv-Nginx)下载已经配置好的nginx
2. 安装里面的ca证书，放在受信任的机构或者个人里
3. 将系统的hosts替换成里面的，并把`210.129.120.50   app-api.pixiv.net`改成`127.0.0.1  app-api.pixiv.net`
4. 启动nginx

然后就可以访问p站了

**Comment by Mapaler** [comment]
如果不需要修改修改PUBD程序，那需要我更新什么？

**Comment by MoveCloudROY** [comment]
emmm
好像很有道理

**Comment by MoveCloudROY** [comment]
emmm

**Comment by MoveCloudROY** [comment]
可能可以加入到wiki里吧

**Comment by Mapaler** [comment]
已添加
