### ISSUE TITLE
能否支持无损的动图下载

### ISSUE THREAD

**Issue by maplestory03** [Mapaler/PixivUserBatchDownload#45]
看到之前的讨论说ZIP会压缩，而且背景不会透明。
能否下载时候把无损的格式转换成压缩格式，在设置里能选择格式zip、rar、ugoira
如果不行的话在设置里添加一个选择下每一帧还是下zip格式的选择吧
另外可否在关注中做一键下载公开、非公开画师（批量画师下载），
自己的公开和非公开收藏（批量下载自己收藏）
下了几个画师，总的来说这款插件很棒！

**Comment by Mapaler** [comment]
p站只提供了压缩的zip和原始帧，没有打包的原始帧，想解决这个问题必须要建一个第三方服务把每一帧下载后打包，你再从第三方服务下载，但是我没有时间和金钱来做这个事情。
目前个人可以考虑把动图帧下载到一个独立文件夹，自己手动打包。
直接下zip、批量画师下载我目前没空懒得做。
自己的收藏图片可以在自己首页下啊，把自己当成画师访问就行了。私人收藏看这里 https://github.com/Mapaler/PixivUserBatchDownload/wiki/%E8%87%AA%E6%94%B9%E4%BB%A3%E7%A0%81

**Comment by maplestory03** [comment]
> p站只提供了压缩的zip和原始帧，没有打包的原始帧，想解决这个问题必须要建一个第三方服务把每一帧下载后打包，你再从第三方服务下载，但是我没有时间和金钱来做这个事情。
> 目前个人可以考虑把动图帧下载到一个独立文件夹，自己手动打包。
> 直接下zip、批量画师下载我目前没空懒得做，本职工作有点忙。
> 自己的收藏图片可以在自己首页下啊，把自己当成画师访问就行了。私人收藏看这里 https://github.com/Mapaler/PixivUserBatchDownload/wiki/%E8%87%AA%E6%94%B9%E4%BB%A3%E7%A0%81

那么复杂就算了，下载设置里添加一个下动图的分类选择（下压缩zip、下原图帧以及两者下）这样可以吗？

**Comment by Mapaler** [comment]
zip有两个尺寸，600×600和1920×1080，下哪个？zip的命名规则和图片不一样，怎么用掩码？

**Comment by maplestory03** [comment]
不清楚2个格式是不是都有，优先下1080，没有就下600。老版本记得是可以下zip的，那时命名规则是怎么区分的，关于掩码才看了下文档，还比较懵，只知道是提取数据用。
