### ISSUE TITLE
关于token有效期是否可以增加

### ISSUE THREAD

**Issue by maplestory03** [Mapaler/PixivUserBatchDownload#47]
关注的比较多画师，按每50个画师批量打开，然后用模拟按键下一批，等下完了再继续下一批。
这样经常会要反复登陆，不知道这个有效期是否跟P站有关？
自己根据代码修改过超时时间，但实际还是1小时就要重新登录了。

**Comment by Mapaler** [comment]
这个时间是P站官方限定的，手机APP API登陆返回的token限制就是3600秒。我做过测试，手机APP，如果长时间不做操作，也是需要重新获取token的。

**Comment by maplestory03** [comment]
好吧，那就没办法了
