### ISSUE TITLE
TamperMonkey扩展菜单中没有按钮

### ISSUE THREAD

**Issue by hayashiretsu** [Mapaler/PixivUserBatchDownload#48]
如题：
虽然脚本已经安装，但在扩展菜单中并没有出现“PUBD-下载该画师”及“PUBD-选项”两个按钮；
（Aria2和webui-aria2都已经配制好了）
求解决

**Comment by Mapaler** [comment]
![Screenshot_2019-09-06-14-32-57](https://user-images.githubusercontent.com/6565860/64406001-3fd29700-d0b3-11e9-8c43-9e194d6058fe.png)
在P站页面才会出现的。
如果还有问题请按F12打开开发者工具，将控制台的错误截图给我看。（当然我这是没有问题的）
![Screenshot_2019-09-06-14-34-57](https://user-images.githubusercontent.com/6565860/64406101-888a5000-d0b3-11e9-8101-169d8a1c0635.png)

**Comment by hayashiretsu** [comment]
![无标题](https://user-images.githubusercontent.com/54969599/64416930-aca55b80-d0ca-11e9-8847-755bc62feb3b.png)
现在是这样的，确实是在p站界面下的= =

**Comment by Mapaler** [comment]
已确认在Chrome下有这个BUG，请等待修复

**Comment by Mapaler** [comment]
已修复

**Comment by hayashiretsu** [comment]
神速0 0 多谢！
