### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by c1araliang** [Mapaler/PixivUserBatchDownload#5]
debian + lantern 成功连接rpc模式，下载输出：
```
04/25 10:55:03 [ERROR] CUID#816 - Download aborted. URI=http://i4.pixiv.net/img-original/img/2012/01/18/20/54/33/24455711_p0.jpg
Exception: [SocketCore.cc:794] errorCode=1 接收数据失败, 原因: Connection reset by peer

```
打开链接也是403 Forbidden nginx
奇怪了，两天前 ubuntu + lantern 操作没有任何问题。系统环境下也可以联网。

**Comment by Mapaler** [comment]
lantern 是什么？Linux下也有Aira2啊。网上搜的

> 常出现的Connection reset by peer: 原因可能是多方面的，不过更常见的原因是： 
①：服务器的并发连接数超过了其承载量，服务器会将其中一些连接Down掉； 
②：客户关掉了浏览器，而服务器还在给客户端发送数据； 
③：浏览器端按了Stop  

你看看你的设置是不是并发下载太多？

直接打开链接403是肯定的，因为需要Referer。脚本是会把Referer发送给Aria2的。

**Comment by c1araliang** [comment]
lantern是爬墙软件，移动网下P站已挂..
并发下载是1，我用的是chrome，不管手动开关referer扩展都是error😂。

**Comment by Mapaler** [comment]
你看看浏览器端你发送的时候，post里referer有没有发送正确。
![image 7](https://cloud.githubusercontent.com/assets/6565860/14812259/fccfeb62-0bce-11e6-99ab-fd129482ac29.jpg)

**Comment by c1araliang** [comment]
Referer:http://www.pixiv.net/member_illust.php?id= 
referer是正确的，猛然发现webui失败时显示active：5，可我设置的max-connection-per-server=1，不知道和这个有关吗。

**Comment by Mapaler** [comment]
这个referer不正确吧，这是用户作品列表页面，而不是作品信息页面，再说id呢？
你试试改脚本设置的引用页面（Referer）为“http://www.pixiv.net/”然后试试？也就是全部用固定的“http://www.pixiv.net/”来下载。

**Comment by c1araliang** [comment]
是lantern的锅 referer应该是对的  抱歉抱歉抱歉(　；∀；)！！！ 
手动增加 http-proxy 就 成功了！

**Comment by Mapaler** [comment]
你说的这些我都不懂啊，我只会Windows。
