### ISSUE TITLE
当前作品为gif的时候没有下载当前作品选项。。

### ISSUE THREAD

**Issue by lgq1349422030** [Mapaler/PixivUserBatchDownload#50]
![image](https://user-images.githubusercontent.com/57399652/69433376-7ba60000-0d76-11ea-90b8-7eadb1014642.png)

开启自动获取数据的话，点击`使用PUBD扒图`会
![image](https://user-images.githubusercontent.com/57399652/69433531-b5770680-0d76-11ea-9e79-6ba728afaa68.png)

而在画师主页选择下载所有作品是能够发现并下载动图的

**Comment by Mapaler** [comment]
请给我这个链接我好研究

**Comment by lgq1349422030** [comment]
https://www.pixiv.net/artworks/72952572

**Comment by Mapaler** [comment]
已修复
