### ISSUE TITLE
只要曾经关注过画师，按钮就会莫名奇妙消失

### ISSUE THREAD

**Issue by wellsun** [Mapaler/PixivUserBatchDownload#52]
刚更新的版本，然后发现只要是关注的画师按钮就会不见了，取消关注也没用，只有没被关注过的画师才是正常的

**Comment by Mapaler** [comment]
![Screenshot_2019-11-25-20-22-25](https://user-images.githubusercontent.com/6565860/69540393-7688c100-0fc1-11ea-8821-94fab5287060.png)
我无法复现你的情况。
请告诉我一些详细信息，在控制台看看有什么报错？

**Comment by wellsun** [comment]
突然又好了……暂时不知道当时是什么情况
