### ISSUE TITLE
针对作品页，下载当前作品选项消失

### ISSUE THREAD

**Issue by lgq1349422030** [Mapaler/PixivUserBatchDownload#53]
![Uploading image.png…]()
尝试了切换浏览器，降级脚本等操作，均无下载当前作品选项

**Comment by Mapaler** [comment]
![图像 19](https://user-images.githubusercontent.com/6565860/72820067-5287ea00-3ca9-11ea-96ac-ce4d05e0432a.png)
你的图片没上传成功，而我这里是能用的

**Comment by lgq1349422030** [comment]
我改了下代码

**Comment by lgq1349422030** [comment]
用原本的代码的话，我这里是
![image](https://user-images.githubusercontent.com/57399652/72820723-549e7880-3caa-11ea-80d0-23b74f16801b.png)
![image](https://user-images.githubusercontent.com/57399652/72820749-65e78500-3caa-11ea-8583-d4f73c54a401.png)
似乎我这里的pixiv改了UI？

**Comment by Mapaler** [comment]
有可能的，P站经常是部分用户改UI。另外你可以试试按钮

![图像 20](https://user-images.githubusercontent.com/6565860/72822170-9cbe9a80-3cac-11ea-8f21-a01dd7aeae3f.png)
