### ISSUE TITLE
对新版Edge不适配

### ISSUE THREAD

**Issue by MoveCloudROY** [Mapaler/PixivUserBatchDownload#55]
rt

**Comment by Mapaler** [comment]
我是针对火狐+Tampermonkey开发的，Chrome应该能用

**Comment by MoveCloudROY** [comment]
对,chrome能用，我是在尝试换浏览器时发现的
但为什么同样的内核，edge不能用，感觉是个玄学问题

**Comment by Mapaler** [comment]
我都没有被更新到新版edge，没法测试

**Comment by Sonic853** [comment]
我这里的版本是 Edge 83.0.478.18 走的 Beta 通道，
去年用到现在基本上没有发现有什么大问题0.0
