### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by 1339090175** [Mapaler/PixivUserBatchDownload#57]
![image](https://user-images.githubusercontent.com/61870765/77726459-e02de000-7032-11ea-8352-2d384ccf0123.png)
怎么登陆

**Comment by Mapaler** [comment]
这种可能跟网络IP被P站禁止有关，其他网友又出现这个情况的换梯子就能进去了。

**Comment by 1339090175** [comment]
![image](https://user-images.githubusercontent.com/61870765/77732012-fb9ee800-703e-11ea-9456-67f757ae569b.png)
显示登陆成功，但登录页面不会消失

**Comment by Mapaler** [comment]
你的使用顺序不对，需要先到设置里开器登陆，填写账号信息的。

其实这是历史遗留问题，以前是可以不登陆访问非R18的，后来P站改成了所有的必须登录。然后你没按照操作顺序先去开启登录，这里就出现了意外的BUG。

**Comment by Mapaler** [comment]
先在设置中启用登陆，并且记得要“保存”设置哦，不然还是不会存的。

**Comment by 1339090175** [comment]
已解决，感谢！
