### ISSUE TITLE
冒昧地问一下，速度这么慢的吗？

### ISSUE THREAD

**Issue by 1339090175** [Mapaler/PixivUserBatchDownload#58]
![image](https://user-images.githubusercontent.com/61870765/77744730-fe0c3c80-7054-11ea-9e2f-59e5f3908527.png)

**Comment by Mapaler** [comment]
Aria2有自己的代理设置，你没设置的话，就是直连P站的（图片的域名没被墙）。
因为我考虑到直连可以节省代理的流量，所以是没给Aria2的默认配置加代理的。

设置代理请参阅 https://aria2.github.io/manual/en/html/aria2c.html#http-ftp-sftp-options
