### ISSUE TITLE
尝试了很多种办法 但是一直显示Oh Snap! Could not connect to the aria2 RPC server. Will retry in 10 secs. You might want to check the connection settings by going to Settings > Connection Settings

### ISSUE THREAD

**Issue by lukesteven** [Mapaler/PixivUserBatchDownload#6]
很多人有这问题 办法都试了就是连不上服务器 这应该怎么办呢麻烦了

**Comment by Mapaler** [comment]
你说的webui-aria2？你们要确保aria2没有被防火墙阻断，然后本地服务器连接地址从localhost改成127.0.0.1（怕hosts被改掉了）。

**Comment by lukesteven** [comment]
好的谢谢了 我等下去试试

**Comment by Mapaler** [comment]
第二个问题，可以直接试cmd命令 `ping localhost` ，如果很快就ping通那就可以排除。第一个问题只有看防火墙设置了。

**Comment by Mapaler** [comment]
其实直接在我的脚本里点击按钮测试连接就行了，能连上的话不超过3秒就会显示版本。
确保你运行的aria2显示的端口也是和设置的一样（默认6800）

**Comment by Mapaler** [comment]
如果还不行，就可能是端口已被占用，尝试更换aria2的端口，设置文件添加
`--rpc-listen-port=<端口数字>`

    可选值: 1024 -65535

然后修改脚本和webui的服务器端口设置。

**Comment by lukesteven** [comment]
好了好了 谢谢了

**Comment by Mapaler** [comment]
所以是哪个问题？

**Comment by lukesteven** [comment]
我没开aria2.... 双击以为打开了
