### ISSUE TITLE
在脚本中配置aria2失败

### ISSUE THREAD

**Issue by btdwv** [Mapaler/PixivUserBatchDownload#61]
填写Aria2 JSON-RPC 路径后，点击“检查路径”会提示失败
网页控制台有这行提示 Refused to connect to "http://Aaia2的地址": URL is not a part of the @connect list

没有提示联网要求，允许网络请求之类的东西
后来我手动在Tampermonkey中设置，“用户域名白名单”中加入aria2的ip，之后检查才能成功
可以考虑一下，加入相关说明

**Comment by Mapaler** [comment]
每个人远程Aria2的域名都不一样，我不可能全部写得进去。
Tampermonkey 首次连接非指定域名的时候，会弹出询问的，但是有时间限制，是不是你把那个忽略掉了？
