### ISSUE TITLE
Pixiv 出了夜间模式（正在测试），开启夜间模式后下载工具里的文字大部分变白

### ISSUE THREAD

**Issue by Sonic853** [Mapaler/PixivUserBatchDownload#63]
浏览器：Edge 83.0.478.18 Beta 通道
使用的插件：Tampermonkey 4.10
脚本版本： 5.10.95

截图：
![Snipaste_2020-05-05_02-21-52](https://user-images.githubusercontent.com/8389962/80999996-2b2fe400-8e78-11ea-9c85-0caabcbd7680.png)

BUG 复现方法：
1. 进入 Pixiv ，打开一个画师的作品，点击右上角的用户头像右边的下拉按钮，点击“夜间模式(测试中)”开关。
2. 打开“使用 PUBD 扒图”
3. BUG 复现。

PS：这个 BUG 应该无关紧要（而且夜间模式还在测试），如果弄好了 close 即可 2333

**Comment by Mapaler** [comment]
其实就是css问题吧，到时候把文字固定成黑色就行了。

**Comment by Sonic853** [comment]
> 其实就是css问题吧，到时候把文字固定成黑色就行了。

或者迎合夜间模式跟着把面板背景调成黑色也可以 2333
（这样子会更麻烦吧？
