### ISSUE TITLE
关于动图存储

### ISSUE THREAD

**Issue by maxphoenixwayne** [Mapaler/PixivUserBatchDownload#64]
我不知道是我没看到使用说明这一项还是真没有，保存动图会给我逐帧拆成JPG文件

**Comment by Mapaler** [comment]
P站下载动图是包含压缩的jpg序列的zip包，用程序控制绘制到画布上，并没有动图格式。我的程序下载的是作者上传的原始图片。
你去看看传动图的上传方式就明白了。

**Comment by Mapaler** [comment]
只有作者将gif或apng本身以单张插画上传才能直接下载到动图。所有以动图模式上传的动画要获得动图格式都必须下载后再转换。

**Comment by maxphoenixwayne** [comment]
谢谢解答
