### ISSUE TITLE
Aria2 JSON-RPC 路径这个到底要怎么填？

### ISSUE THREAD

**Issue by 354286237** [Mapaler/PixivUserBatchDownload#67]
百度搜索后把主机名字填上去了 但是端口号不知道是啥 按百度上说的一搜索 有几十个端口号啊 看着就头疼 试了几个都说链接失败 到底要怎么搞啊？

**Comment by Mapaler** [comment]
本机ip是127.0.0.1，或者用域名localhost。默认端口是6800。
如果你启动时防火墙给禁了的话，那么就连不上。

**Comment by 354286237** [comment]
> 本机ip是127.0.0.1，或者用域名localhost。默认端口是6800。
> 如果你第一次启动时的联网请求，防火墙给禁了的话，那么就连不上。

终于搞好了…… 原来这个aria2需要启动的 我以前一直都没启动……

**Comment by a1193095382** [comment]
好的，3Q，昨天已经解决了。这个脚本的确厉害，就是有些麻烦hh。
