### ISSUE TITLE
部分图片出现文件损坏

### ISSUE THREAD

**Issue by lich13** [Mapaler/PixivUserBatchDownload#7]
求问可否通过修改aria2参数来解决问题？

**Comment by Mapaler** [comment]
你可以尝试重新下一遍，aria2默认打开了continue参数，会自动断点续传。

**Comment by lich13** [comment]
所有参数都确定没问题 应该是aria2的锅 换了idm同时下再多也没出现过坏图 建议下个版本的生成直接链接里可以一次性全部选定方便导入idm 不然要按住滚轮往下拖太辛苦了

**Comment by Mapaler** [comment]
你直接右键全部下载到idm不就行了么。我还是会继续用aria2的，毕竟很多高级功能得用这个才行。

**Comment by lich13** [comment]
全部下载到idm会有一个漫长的筛选过程 而且筛选之后会被p站官方弹出登录 [https://public.lightpic.info/image/121C_578C1D120.jpg](url)建议能在这个页面加一个全部选定或者导出为文本的功能就可以最大化满足idm用户的需求了 并不需要后续支持 如果能采纳的话不胜感激- -另外3.2.1版本使用默认设置RPC会只下第一张图 版本换回2.6.0正常 坏图的原因也和时间段有关 晚上p站的服务器质量差一点 早上下的话就会速度很快没有坏图（但是主要还是在晚上下载需求高

**Comment by Mapaler** [comment]
为什么会有一个漫长的筛选过程？弹出登录又是什么意思？全部选定这个应该无法支持，网页内脚本并没有控制浏览器的权限。
![image 1](https://cloud.githubusercontent.com/assets/6565860/16904411/2bbc2f6e-4cc8-11e6-8290-869bdc82c83f.png)
但是只要这样做就能全部选中了，从框的上外部拖到下外部。

导出文本，你确定不用referer能下载？而且保存路径又怎么办？
我一直都在用最新版本，并没有出现只下载第一张图的问题。因为俩版本差异比较大，你最好重置设置尝试一下。
Aria2的设置是很丰富的，我提供的只是最基础的一些，你可以尝试增加等待时间、重试次数等。我一般都是发现有错误的，重新添加一遍下载，有下载好的会自动跳过，下载失败的会断点续传。

```
#断点续传，默认打开的
continue=true
# 禁用覆盖（跳过已下载的）
allow-overwrite=false
# 禁用重命名（跳过已下载的）
auto-file-renaming=false
```

**Comment by lich13** [comment]
感谢提供技巧 我指的是文本是用于idm/迅雷这种软件的 现在感觉无所谓了 ARIA2的参数我都有仔细了解调试过了 感觉还是程序硬伤 验证了导致只下一张图的原因是我把下载路径留空了 然而并没有正常调用aria2的默认路径 算是个小bug吧 “v3.2已改变路径获取方式，不需要这样设置了，不重置也可以用，但是为了规范新路径格式还是建议重置”加了%{user_id}的使用体验感觉不如不加啊

**Comment by Mapaler** [comment]
因为动图自动转gif的技术难题不知道怎么解决比较好（无法发送信息到本地），所以一直坑着没做。那个路径格式你按照自己喜爱的来设置就行了。

**Comment by lich13** [comment]
另外是否有可能通过注册浏览器协议网页直接调用vbs？例如Pixiv Animat Downloader http://s.weibo.com/weibo/Pixiv%2520Animat%2520Downloader%2520v1.0.0.5?topnav=1&wvr=6&b=1#1468810398698

**Comment by Mapaler** [comment]
C#不怎么会编啊，我喜欢绿色还是觉得RPC比较好，可惜Aria2的RPC没有可以用来写注释的地方，不然难度就会低很多。

**Comment by lich13** [comment]
往vbs里加了一个清理图标缓存的bat 感觉使用体验有提高 不然图标总是不变很蛋疼 建议考虑加入这个功能

**Comment by Mapaler** [comment]
我当然也想搞，但是不知道怎么刷新。

**Comment by lich13** [comment]
http://zhidao.baidu.com/link?url=5VrLgeEgI31YOWTezuC14Gb-sNa_7_KhurQVFflboGwqvxzgqRnE4YxkqUyXDfYsn7Xi3GzPu41oc74ll6C41_
百度找了个bat 往PUBD_customize_folder.vbs里加了一行 `CreateObject("WScript.Shell").Run "D:\Data\1\NConvert-win64\a.bat",0` 就刷新了 我不是太懂原理 就乱试的 不要见笑哈

**Comment by Mapaler** [comment]
看起来是删除了缓存的文件。我本来是计划让这个更换图标变成自动操作的，不过结构没想好。

**Comment by lich13** [comment]
3.2使用了几天感觉除了路径bug其他方面都十分稳定 加了aria2的等待时间之后坏图也几乎没有了 提醒的优化比2.6舒服太多了 要是bilibili的视频也能这么方便的导出aria2管理就好了

**Comment by Mapaler** [comment]
那个torrent和其他文件不一样，需要指定dir才行，如果路径留空的话，就不知道正确的文件夹了。为什么你要留空呢？

**Comment by Mapaler** [comment]
我最近事情多，不过这两天还是抽空把路径bug解决了，已经更新了。

**Comment by lich13** [comment]
现在已经基本确定文件损坏是网络本身的问题 顺带发现个能自动转换动图的项目 https://github.com/Nandaka/PixivUtil2/commit/ce0a52aee22e5a6c8d9b75580016666081fa7458 希望可以考虑借鉴下 他这个没法多线程下载好不方便的

**Comment by Mapaler** [comment]
文件损坏，重新添加一遍下载，会自动续传。他这是属于本地下载的方式，当然可以在本地进行图片处理，然而我没有在本地造轮子，只通过RPC把下载信息发送给Aria2而已。而Aria2又没有可以附带其他信息的手段，因此很难再在本地进行智能的图片处理。

**Comment by JJcdomat** [comment]
“生成直接链接”希望可以改文件名为真实URL，因为无法直接复制全部URL，而只要能复制URL，就可以导入idm。
另外 @lich13 ，chrome可以下载[Linkclump](https://chrome.google.com/webstore/detail/linkclump/lfpjkncokllnfokkgpkobnkbkmelfefj)来选择直接复制URL到剪切板希望可以帮到你。

**Comment by lich13** [comment]
@JJcdomat 感谢分享

**Comment by Mapaler** [comment]
经过对该选项的实用性与人性化难度评估后，**决定不予开发**。现在的方式，保存路径设置是会改变链接名称的，方便归类下载到不同文件夹。
![image 2](https://cloud.githubusercontent.com/assets/6565860/19084079/975a3af6-8a97-11e6-9c0d-c227ec6182d6.png)
如果只生成链接无法达到效果，但是如果另外开发一个只生成链接的功能会增加程序框架复杂性，目前也没有一个容易修改的部分给它用。
