### ISSUE TITLE
PUBD按钮没有出现在书签页面上

### ISSUE THREAD

**Issue by niconicocolonel** [Mapaler/PixivUserBatchDownload#70]
现在，Pixiv有一个按用户ID的书签页面（https://www.pixiv.net/users/ID/bookmarks/artworks ）
和一个专门的书签页面（https://www.pixiv.net/bookmark.php ）。

在最近的一次更新中，PUBD按钮不再出现在后者的书签页面上。

**Comment by Mapaler** [comment]
是的，为了降低代码复杂程度，目前停止对老版框架的支持，是为了专注于把新框架的体验做好。

既然你还要用的话，我刚才已经把老版页面的支持兼容性加回去了，不会在老板页面上进行新功能的开发。

**Comment by niconicocolonel** [comment]
首先，感谢您的回复。5.11.105版本是老板页面的按钮显示。 并表示老板页今后不会再有任何附加功能。 我了解发展状况。

**Comment by Mapaler** [comment]
结果我发现手机版还是有类似老的结构，又修改了一定的兼容性
