### ISSUE TITLE
收藏数量过大的情况

### ISSUE THREAD

**Issue by ducamg0503** [Mapaler/PixivUserBatchDownload#71]
# 画师的收藏数量>7000的情况
* 进程日志出现：错误信息：Rate Limit 
* 但是过一段时间，重新点击"他的收藏"又会继续爬取，但是又会出现Rate Limit
![img](https://user-images.githubusercontent.com/53567309/87242019-7e677980-c45b-11ea-843d-d5bc3cb3d14f.png)

**Comment by Mapaler** [comment]
你把页面发给我测试一下

**Comment by ducamg0503** [comment]
> 你把页面发给我测试一下

https://www.pixiv.net/users/1267809/bookmarks/artworks

**Comment by Mapaler** [comment]
我检查了，发现这个就是速度限制，短时间内请求次数过多就会出现这个。
解决方法只能是减慢请求速度，比如每次获取隔个几秒

**Comment by Mapaler** [comment]
如果你需要减慢请求速度的话，可以改代码，但是其他的也会一起变慢。

**Comment by ducamg0503** [comment]
> 如果你需要减慢请求速度的话，可以改代码，但是其他的也会一起变慢。
可以按照爬取的收藏数来进行减慢，爬取数量小的话就不用减速了。如果爬取过大，可以稍微减速，不然隔一段时间就会出现Rate limit

**Comment by ducamg0503** [comment]
> 如果你需要减慢请求速度的话，可以改代码，但是其他的也会一起变慢。

可以按照爬取的收藏数来进行减慢，爬取数量小的话就不用减速了。如果爬取过大，可以稍微减速，不然隔一段时间就会出现Rate limit

**Comment by Mapaler** [comment]
那么到底多少才是大，减慢多少？

**Comment by ducamg0503** [comment]
> 那么到底多少才是大，减慢多少？

这个我也不清楚

**Comment by Mapaler** [comment]
![Screenshot_2020-08-10-20-15-22](https://user-images.githubusercontent.com/6565860/89783774-171c1280-db4a-11ea-9202-65f819f66e00.png)
![Screenshot_2020-08-10-20-15-37](https://user-images.githubusercontent.com/6565860/89783776-184d3f80-db4a-11ea-83aa-afb76f0b8c54.png)
![Screenshot_2020-08-10-20-28-42](https://user-images.githubusercontent.com/6565860/89783779-197e6c80-db4a-11ea-98a1-66e6d09f93c0.png)
目前做了这三个功能，还在测试
