### ISSUE TITLE
使用不逐项（按作者）无法发送到Aria2。。。

### ISSUE THREAD

**Issue by Kiana977** [Mapaler/PixivUserBatchDownload#72]
选项里选不逐项就会提示发送到Aria2失败，只要选另外两个就可以下载没有问题。但是不按作者分类的话下载下来会有很多的文件夹我整理不方便，请问一下如何解决！！！
![QQ截图20200714091412](https://user-images.githubusercontent.com/49866998/87369181-73732d00-c5b2-11ea-9136-4993409a234e.png)

**Comment by Kiana977** [comment]
已经好久了，我过了几个礼拜再去下载也是这样提示。

**Comment by Mapaler** [comment]
如果你一次发送的文件太多，超出了http post接收上限，Aria2就会接受失败。一般那种几万张图的作者就会有这个问题。

选择逐项，只是分开发送下载信息，下载文件夹是根据你的掩码来的，与是否逐项无关。

不逐项发送的目的只是为了加快发送速度。你可以理解为不逐项就是一辆公交车，一辆装不下就要每次少装一些，多装几次。

**Comment by ghostvarg** [comment]
非常感谢，终于明白是怎么搞远程的了！太感谢了！
