### ISSUE TITLE
[建议] token可从网页自动获取或可自定义会话时长

### ISSUE THREAD

**Issue by newtimeforC** [Mapaler/PixivUserBatchDownload#73]
每次使用时都要登陆,而且每次使用时间和频率不一样,有时单次会话时间不够又要重新登陆,虽然可以记住密码使用上没什么,但是如果能从网页获取会话持续时间就更好了

**Comment by Mapaler** [comment]
我找过，API不一样，Token不通用，网页的API又经常改，用起来麻烦得很
