### ISSUE TITLE
简写的“作品发布时间”的代码失效了

### ISSUE THREAD

**Issue by FlareMonso** [Mapaler/PixivUserBatchDownload#74]
%{var dt=new Date(illust.create_date)}%{dt.getFullYear()}年-%{dt.getMonth()+1}月-%{dt.getDate()}日
这段代码输出为“年-月-日”

**Comment by Mapaler** [comment]
可能是因为代码升级到严格模式导致的，目前的解决办法就是不要使用简写。
`%{new Date(illust.create_date).getFullYear()}年-%{new Date(illust.create_date).getMonth()+1}月-%{new Date(illust.create_date).getDate()}日`

或者使用ES6写法的函数表达式来获取简写（未来的PUBD6会切换写法，目前就这样用着吧）
`%{(dt=>dt.getFullYear()+"年-"+(dt.getMonth()+1)+"月-"+dt.getDate()+"日")(new Date(illust.create_date))}`
