### ISSUE TITLE
登录的时候一直显示账号或密码不正确

### ISSUE THREAD

**Issue by Endousan** [Mapaler/PixivUserBatchDownload#78]
你好，请问下，我在登录的时候一直显示账号或密码不正确，但我账号密码都是能登录到PIXIV的。

**Comment by Mapaler** [comment]
请先尝试是否能用帐号密码登录pixiv官方手机APP。再用同样的帐号密码登录本脚本。

**Comment by Endousan** [comment]
好的，感谢，我尝试了一下，APP不能登录了，我修改了密码，就好了，我一直保存的密码，不知道怎么回事今天就出错了
