### ISSUE TITLE
P站的API又更新了么？现在RPC完全没速度。

### ISSUE THREAD

**Issue by shengop** [Mapaler/PixivUserBatchDownload#79]
//
Exception: [SocketCore.cc:874] errorCode=1 Failed to receive data, cause: An existing connection was forcibly closed by the remote host.

**Comment by Mapaler** [comment]
`i.pximg.net`被墙了，需为Aria2设置代理了
[Aria2 通过代理下载](https://github.com/Mapaler/PixivUserBatchDownload/wiki/Aria2%e9%80%9a%e8%bf%87%e4%bb%a3%e7%90%86%e4%b8%8b%e8%bd%bd)

**Comment by Mapaler** [comment]
目前是P站自己炸了，直接进不去

**Comment by JCMakoto** [comment]
yup，p站直接炸裂，下载不到了，一直提示“证书链是由不受信任的颁发机构颁发的”

**Comment by shengop** [comment]
> yup，p站直接炸裂，下载不到了，一直提示“证书链是由不受信任的提交机构提交的”
你可能需要再你的INI里把这项设置为：check-certificate=false

**Comment by shengop** [comment]
> `i.pximg.net`被墙了，需为Aria2设置代理了
> [Aria2通过代理下载](https://github.com/Mapaler/PixivUserBatchDownload/wiki/Aria2%e9%80%9a%e8%bf%87%e4%bb%a3%e7%90%86%e4%b8%8b%e8%bd%bd)
果真是被墙了，现在已解决！
