### ISSUE TITLE
單圖要如何變成單一資料夾

### ISSUE THREAD

**Issue by PingStyle** [Mapaler/PixivUserBatchDownload#8]
在"多圖"情況下的時候 可以很方便的自動把標題抓來命名資料夾檔名

但"單圖"時 他並不會自動建立資料夾 

請問下載"單圖"的情況下
要如何變成自動建立單圖資料夾與自動命名標題

謝謝

**Comment by PingStyle** [comment]
單圖下載下來   檔名只有一串數字  沒辦法分辨這張圖原本的標題與名稱
http://i.imgur.com/2scTHPc.jpg
我在單圖那欄打上
%{title}

一樣下載下來會是一串數字....
這樣無法辨認這張圖阿...尤其有的畫師是長期連載一個系列
有時是多圖  有時卻只有一張圖
能否解答一下  
下載"單圖"的情況下
要如何變成自動建立單圖資料夾與自動命名標題
謝謝Q_Q

**Comment by Mapaler** [comment]
多图掩码%{multiple}和类型命名%{type_name}其实程序本质上都是一样的；区别是多图掩码只在多图的时候起作用，其他时候为空值；类型命名在每一种都起作用。v2.x的时候文件保存名里默认就有多图掩码的内容，最新的 v3.4.3为了兼容新技术（虽然现在不是很好用）都已经没有默认使用了。
而类型命名从来默认没有使用的，你可以在这里给不同的类型使用不同的掩码，程序会自动将%{type_name}替换成你设置的内容。如果你所有类型都要有相同的处理（多一层title的文件夹），直接在保存路径改就是了，不需要用类型命名。
用这个画师做实例[ask](http://www.pixiv.net/member_illust.php?id=17678931)
![image 3](https://cloud.githubusercontent.com/assets/6565860/21016035/21473770-bd9f-11e6-9784-2bae5171ebb0.png)
这个设置得到的结果如下
![image 4](https://cloud.githubusercontent.com/assets/6565860/21016879/4a0d4b6a-bda2-11e6-844b-07a1df2eeb34.png)

如果你是希望图片文件本身的文件名变为标题的话，那么把末尾的%{filename}.%{extention}改成%{title}.%{extention}就可以了。但是这样碰到同名插图或多图就会产生重名，建议加上独占标识符，比如%{illust_id}\_%{title}\_%{page}.%{extention}。

想要查看输出的保存路径到底是什么的话，用“生成直接链接”就可以看到了。
![image 5](https://cloud.githubusercontent.com/assets/6565860/21016669/67b7fdc8-bda1-11e6-9f7e-9d6dc840403e.png)

**Comment by Mapaler** [comment]
又给个示例，具体怎么设置掩码按此举一反三吧。%{filename} 其实相当于 %{illust_id}_p%{page} ，整个P站都不会重名的（少数情况下还会有个%{hash}这里不做讨论）。
![-1](https://cloud.githubusercontent.com/assets/6565860/21017131/485340d0-bda3-11e6-9a57-c3176b9ff5ef.png)
画师文件夹只用画师id的原因是，画师们经常取“大嘘＠三日目Ａ77b”这种名字，每次展会都会变，如果写到文件夹路径里就经常变化导致重复下载到一个新的文件夹，而id绝对不变。
