### ISSUE TITLE
教教  救救

### ISSUE THREAD

**Issue by EvilDrawsClose** [Mapaler/PixivUserBatchDownload#80]
01/29 12:54:04 [ERROR] CUID#14 - Download aborted. URI=https://i.pximg.net/img-original/img/2021/01/23/21/43/44/87250458_p0.jpg
Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by Mapaler** [comment]
看 #79
