### ISSUE TITLE
Aria2 JSON-RPC 路径应该填什么

### ISSUE THREAD

**Issue by Mstsuka** [Mapaler/PixivUserBatchDownload#84]
一直显示连接失败

**Comment by Mapaler** [comment]
你在电脑上启动了Aria2吗？Aria2不能关闭。
`http://127.0.0.1:6800/jsonrpc`是默认的连接本机的Aria2的路径

**Comment by Mstsuka** [comment]
感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "枫谷剑仙"<notifications@github.com&gt;; 
发送时间: 2021年2月28日(星期天) 凌晨1:51
收件人: "Mapaler/PixivUserBatchDownload"<PixivUserBatchDownload@noreply.github.com&gt;; 
抄送: "稍稍坚强的风"<2766447274@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Mapaler/PixivUserBatchDownload] Aria2 JSON-RPC 路径应该填什么 (#84)





 
你在电脑上启动了Aria2吗？Aria2不能关闭。
 http://127.0.0.1:6800/jsonrpc是默认的连接本机的Aria2的路径
