### ISSUE TITLE
为什么aria2下载的速度为0

### ISSUE THREAD

**Issue by puinpuni** [Mapaler/PixivUserBatchDownload#85]
有段时间没用，现在没法下载了，出了什么问题吗

**Comment by puinpuni** [comment]
Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by Mapaler** [comment]
因为 `i.pximg.net` 被墙了，需要给Aria2设置代理

**Comment by puinpuni** [comment]
大佬好，我在aria2_Pixiv.ini文件中加了这么一句
all-proxy=http://A:D@127.0.0.1:E（ABCDE在附件里）
然后报错这个：
CUID#40 - Download aborted. URI=https://i.pximg.net/img-original/img/2021/01/18/17/16/28/87138412_p0.jpg
Exception: [AbstractCommand.cc:313] errorCode=1 Network problem has occurred. cause:No connection could be made because the target machine actively refused it.

想问一下哪里有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mapaler/PixivUserBatchDownload"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月28日(星期天) 晚上9:24
收件人:&nbsp;"Mapaler/PixivUserBatchDownload"<PixivUserBatchDownload@noreply.github.com&gt;;
抄送:&nbsp;"翔"<909967630@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Mapaler/PixivUserBatchDownload] 为什么aria2下载的速度为0 (#85)





 
因为 i.pximg.net 被墙了，需要给Aria2设置代理

**Comment by Mapaler** [comment]
通过邮件回复是不能给github上添加附件的，要上传附件自己上来贴。
不过看你的错误的话，可能你的代理就没连接成功

**Comment by Mapaler** [comment]
新版PUBD可以直接在设置里添加代理，只针对PUBD添加的下载。改ini文件是应用于Aria2全局。

**Comment by Mapaler** [comment]
Aria2目前只支持http代理
https://github.com/Mapaler/PixivUserBatchDownload/wiki/Aria2%e9%80%9a%e8%bf%87%e4%bb%a3%e7%90%86%e4%b8%8b%e8%bd%bd

**Comment by puinpuni** [comment]
![%`@)A3)DYE B(8S2CRB02BL](https://user-images.githubusercontent.com/49758099/109422200-76505000-79d2-11eb-847a-dae6af1bcc60.png)

**Comment by Mapaler** [comment]
你这是SSH隧道代理了
只支持http、https、ftp代理，连socks都不支持。
你这是自己的VPS的话，你要么直接在上面建一个http代理服务器（可能不太安全），要么自己建一个ShadowSocks、V2ray等服务，再用对应本地客户端转发的http代理。

**Comment by Mapaler** [comment]
或者你直接在你的VPS上运行aria2，你直接下载到vps上面去。

**Comment by Mapaler** [comment]
话说你是怎么上的P站，那么让Aria2走同样的渠道就行了。

**Comment by puinpuni** [comment]
![)2KM_~)BGQQ%DW8YUR8A}UO](https://user-images.githubusercontent.com/49758099/109422503-b8c65c80-79d3-11eb-8514-f87de361c76c.png)
我用这个上p站的

**Comment by puinpuni** [comment]
ShadowsocksR

**Comment by Mapaler** [comment]
Shadowsocks系软件 http 代理端口与其socks代理端口一致。你可以自己去设置里看。
![图像 23](https://user-images.githubusercontent.com/6565860/109422641-5bec9580-7a17-11eb-95da-d1cf574df1e9.png)

**Comment by Mapaler** [comment]
你的代理应该只是类似 http://127.0.0.1:1080 这样的。

**Comment by puinpuni** [comment]
跑通啦！跑通啦！谢谢大佬。

**Comment by puinpuni** [comment]
我在网页上设置好像没法保存下来，才想着改ini文件那里

**Comment by Mapaler** [comment]
改ini就是给整个Aria2进程设置代理选项，在PUBD里设置，是每次发送图片下载的时候针对这个下载设置代理。
就是看你要不要用Aria2干其他事情，如果还要下载国内其他的当然就别设置全局的代理了。

**Comment by puinpuni** [comment]
所以现在的下载速度只能和服务器连的速度挂钩了吗，以前几m几m的下，现在才200k

**Comment by Mapaler** [comment]
你可以自行寻找能直连 i.pximg.net 的方法，比如 nginx 反代，我对这方面没有研究。

**Comment by Waitung** [comment]
请问能不能再加个替换下载链接里`i.pximg.net`域名的选项，比如我通过在一台服务器上用域名`ipximg.mydomain.com`做好了反代`i.pximg.net`的准备，这样只需把发送到aria2下载链接里的`i.pximg.net`替换成`ipximg.mydomain.com`也可以下载，一些不方便布置代理的机子可以比较方便下载。

**Comment by Mapaler** [comment]
@Waitung 你这个应该重新开一个issue
