### ISSUE TITLE
更新后页面样式异常 无法使用

### ISSUE THREAD

**Issue by MirrorsAriah** [Mapaler/PixivUserBatchDownload#86]
您好，非常感谢您开发了这款工具。
这里遇到一个异常，更新后P站页面上本工具的按钮样式异常，无法使用。异常情况截图如下。
![1](https://user-images.githubusercontent.com/28749663/109415884-3c914080-79f6-11eb-869d-9a2326462182.png)
![2](https://user-images.githubusercontent.com/28749663/109415887-4024c780-79f6-11eb-86a6-798f461f50db.png)
问题主要表现为页面样式异常，点击选项后弹出无方案对话框（因为上次无法登陆的问题重装过），找不到在哪里调出设置面板。
原本是Chrome浏览器，更换火狐浏览器后有同样的问题。版本是5.16.130版本。
重装工具、重启浏览器无法解决。故向您求助，希望您能抽出宝贵的时间帮忙分析问题的原因。谢谢。

**Comment by Mapaler** [comment]
这是因为Github上的样式没有成功预载，你全局翻墙后刷新一次试试看。

**Comment by MirrorsAriah** [comment]
更换节点后问题解决，非常感谢帮助。
