### ISSUE TITLE
Vivaldi 浏览器获取下载链接后卡在发送链接这一步骤

### ISSUE THREAD

**Issue by lgq1349422030** [Mapaler/PixivUserBatchDownload#88]
![image](https://user-images.githubusercontent.com/57399652/110212907-91422900-7ed8-11eb-83d5-63165c9d52dc.png)

经过测试，我是用Firefox后能够正常发送链接。

Vivaldi的会话保存和界面我真的是特别喜欢，会话保存还能记下浏览的是哪个网页，非常方便

后台标签休眠功能自带，并且支持恢复会话的时候以休眠状态打开保存会话时是休眠状态的标签，对于我这样一次性开一两百个标签页扫图的lsp实在太好用了。

希望能够修一下这个bug，因为我记得之前的版本是正常的，所以应该是个新bug。不然每次都换浏览器保存图片不太方便（其他浏览器新开标签页默认就加载了，非常卡）

**Comment by lgq1349422030** [comment]
问题解决了，vivaldi是27小时前更新的5.16.135版本，我只注意了更新时间和扫了一眼版本号，没注意到版本号最后一位的不同，最新是5.16.136可以正常使用。

**Comment by Mapaler** [comment]
是 #87 提到的改进代码时出现的 bug。
