### ISSUE TITLE
请问能不能再加个替换下载链接里i.pximg.net域名的设置

### ISSUE THREAD

**Issue by Waitung** [Mapaler/PixivUserBatchDownload#89]
由于`i.pximg.net`也被墙了，所以现在加了个**Aria2 代理服务器地址**的设置。
请问能不能再加个替换下载链接里`i.pximg.net`域名的设置，比如我通过在一台服务器上用域名`ipximg.mydomain.com`做好了反代`i.pximg.net`的准备，这样只需把发送到aria2下载链接里的`i.pximg.net`替换成`ipximg.mydomain.com`就可以下载，一些不方便布置代理的机子也可以比较方便下载。

**Comment by Mapaler** [comment]
其实我以前想过，只不过觉得提供给一般人可能改错的可能性更大。

如果要加加这个的话
- [ ] 图片网址https转http

就没必要了。

**Comment by Waitung** [comment]
我认为这个应该问题不大，毕竟现在里面的自定义掩码这块更加复杂，提供多一个设置不会增加使用难度，补充点说明，不需要这个功能的忽略，和以前一样使用就好了。

**Comment by Mapaler** [comment]
已更新v5.17

**Comment by Waitung** [comment]
非常感谢，大佬简直神速

**Comment by Mapaler** [comment]
这部分在我上次修改的基础上改的而已，上次改动花时间一些，本来就是把下载地址超这个方向在统一，这次只不过将固定的改成了掩码。

**Comment by Waitung** [comment]
试了下完全没问题了，总之非常感谢。
