### ISSUE TITLE
通过nginx反向代理如果修改作品下载地址

### ISSUE THREAD

**Issue by ToyamaNao** [Mapaler/PixivUserBatchDownload#90]
![1](https://user-images.githubusercontent.com/31986578/114535789-ff6dce80-9c82-11eb-96ab-2f0385010722.png)
![2](https://user-images.githubusercontent.com/31986578/114535803-01379200-9c83-11eb-966e-770849711991.png)
好久不用发现速度变成是0，然后研究了好久，还是没明白应该在哪里找我通过nginx反向代理后的反向代理域名……

**Comment by Mapaler** [comment]
这里说的是在VPS上自建反代服务器，而不是你的本地。你本地并没有修改反代域名。

**Comment by ToyamaNao** [comment]
> 这里说的是在买的VPS上自建反代服务器，而不是你的本地开的nginx。你本地并没有修改反代域名。

那请问我应该怎么修改……

**Comment by Mapaler** [comment]
速度为 0 是因为 i.pximg.net 在中国境内已经被阻止访问。要么用梯子，要么把 i.pximg.net 也加入本地反代。

我怀疑你根本没更新 Pixiv-Nginx
![Screenshot_2021-04-13-19-59-02](https://user-images.githubusercontent.com/6565860/114548841-dead7500-9c92-11eb-9425-8aa5f7861670.png)

**Comment by ToyamaNao** [comment]
> 速度为 0 是因为 i.pximg.net 在中国境内已经被阻止访问。要么用梯子，要么把 i.pximg.net 也加入本地反代。
> 
> 我怀疑你根本没更新 Pixiv-Nginx
> ![Screenshot_2021-04-13-19-59-02](https://user-images.githubusercontent.com/6565860/114548841-dead7500-9c92-11eb-9425-8aa5f7861670.png)

![QQ截图20210413200814](https://user-images.githubusercontent.com/31986578/114609459-6c0fba00-9cd1-11eb-851c-09bcb62bc837.png)
![QQ截图20210414032557](https://user-images.githubusercontent.com/31986578/114609464-6dd97d80-9cd1-11eb-8f72-3e735ed2bbbd.png)
唔……我是今天刚重新下载的，在hosts里看到有pixiv.pximg.net 呀。看了下下载里面会提示这个

**Comment by Mapaler** [comment]
你直接在浏览器能访问P站的图片吗？

**Comment by Mapaler** [comment]
你这几个错误不是说已经有文件存在了吗？你先自己看看错误的英文再说。

**Comment by ToyamaNao** [comment]
> 你这几个错误不是说已经有文件存在了吗？你先自己看看错误的英文再说。

谢谢，搞明白哪里的问题了。因为遇到重复文件之前不会显示错误，现在会显示错误所以一直以为是还没下过。
现在已经搞定了

**Comment by Mapaler** [comment]
> 谢谢，搞明白哪里的问题了。因为遇到重复文件之前不会显示错误，现在会显示错误所以一直以为是还没下过。

如果是相同文件不会报错，有的作品是作者修改过重投稿的，文件不一样了，而目前的设置是不覆盖旧文件，就会报错。
