### ISSUE TITLE
Aria2发送信息错误

### ISSUE THREAD

**Issue by Ydmy520** [Mapaler/PixivUserBatchDownload#97]
这个是怎么回事？。。。。
![ApplicationFrameHost_AnZ4ghvtLi](https://user-images.githubusercontent.com/84400571/148189301-0ebac328-11da-404b-b96e-50ab7062fb77.png)

**Comment by Mapaler** [comment]
198.168开头的IP不用隐藏吧，都是内网
你的TamperMonkey扩展有没有对这个IP开启白名单，有的人的扩展设置的严格条件，就需要手动添加到白名单才行。
具体操作见
https://github.com/Mapaler/PixivUserBatchDownload/wiki/%E8%BF%9C%E7%A8%8B%E4%B8%8B%E8%BD%BD

**Comment by Ydmy520** [comment]
![ApplicationFrameHost_6OAfU4DknS](https://user-images.githubusercontent.com/84400571/148193122-60cc2991-8c27-44a9-88e3-2a9ac5e0eeb5.jpg)
怕被熟人看见。
添加了，还是不行。

**Comment by Ydmy520** [comment]
怕熟人看见。。
添加了。还是不行，，，
![aasaost_3cU6MJjKdV](https://user-images.githubusercontent.com/84400571/148193758-de526424-e2d0-4e99-aeed-c91d4c31ba23.png)
，

**Comment by Ydmy520** [comment]
![In122223_LI](https://user-images.githubusercontent.com/84400571/148195079-ddc2d931-6eb3-4772-8211-14fc7875a65e.jpg)

**Comment by Mapaler** [comment]
检查这几个方面
1. 你的路由器上的 RPC 配置和扩展里填写的地址正确没有？毕竟我也没法给你debug。
2. 路由器是否有防火墙，对Aria2端口打开入站。
3. Arai2不是很老的版本吧，老版本不支持token，你可以先不要加密码链接试试。

**Comment by Ydmy520** [comment]
感谢，可以用了，我先关了防火墙，又去检查了一边RPC配置，把RPC密钥给注释掉，发现是token的问题，注释掉就能正常用了。aria2是用的这个https://github.com/P3TERX/aria2.sh。这个版本是支持token的吧？。。。。不知道是啥情况等能用了就太好了，自己闭门造车了好几个小时，还是得大佬。。。。。。。。感谢，十分感谢
![chrome_UE6uWgW7bL](https://user-images.githubusercontent.com/84400571/148207563-9b53413f-3c79-4cd1-b9a7-28c3de935d08.png)
版

**Comment by Ydmy520** [comment]
感谢，可以用了，我先关了防火墙，又去检查了一边RPC配置，把RPC密钥给注释掉，发现是token的问题，注释掉就能正常用了。aria2是用的这个https://github.com/P3TERX/aria2.sh/,.这个版本是支持token的吧？....不知道是啥情况等能用了就太好了，自己闭门造车了好几个小时，还是得大佬。。。。。。。。感谢，十分感谢

**Comment by Ydmy520** [comment]
感谢，可以用了，我先关了防火墙，又去检查了一边RPC配置，把RPC密钥给注释掉，发现是token的问题，注释掉就能正常用了。aria2是用的这个https://github.com/P3TERX/aria2.sh/,.这个版本是支持token的吧？....不知道是啥情况，现在能用了就太好了，自己闭门造车了好几个小时，还是得大佬。。。。。。。。感谢，十分感谢

**Comment by Mapaler** [comment]
1.36肯定支持token的，如果你需要使用token的话，按照这个页面写rpc地址，你是不是之前没写？
https://github.com/Mapaler/PixivUserBatchDownload/wiki/%E8%BF%9C%E7%A8%8B%E4%B8%8B%E8%BD%BD
