### ISSUE TITLE
為甚麼每次打開新頁面後，默認下載方案就會消失了

### ISSUE THREAD

**Issue by JasZero** [Mapaler/PixivUserBatchDownload#98]
![001](https://user-images.githubusercontent.com/99342600/153222287-b32dd376-52f6-4b05-8ecb-a75abb0c131d.png)

**Comment by bluefl0werz** [comment]
https://github.com/Mapaler/PixivUserBatchDownload/blob/7f510302ad2572249bd8ee75fc0f27c38373a482/PixivUserBatchDownload.user.js#L1262

**Comment by Mapaler** [comment]
你在设置里选择方案后没有点保存按钮吗？

**Comment by JasZero** [comment]
> 你在设置里选择方案后没有点保存按钮吗？

當然是有按保存了，但如果打開新頁面就會消失要重新新建方案
而且我是一直正常使用然後昨天才出現這個問題

**Comment by JasZero** [comment]
> https://github.com/Mapaler/PixivUserBatchDownload/blob/7f510302ad2572249bd8ee75fc0f27c38373a482/PixivUserBatchDownload.user.js#L1262

這個是? what is this?

**Comment by Mapaler** [comment]
> > 你在设置里选择方案后没有点保存按钮吗？
> 
> 當然是有按保存了，但如果打開新頁面就會消失要重新新建方案 而且我是一直正常使用然後昨天才出現這個問題

是所有的设置都消失了吗？是不是你用了隐私模式？

**Comment by JasZero** [comment]
![002](https://user-images.githubusercontent.com/99342600/153350434-e4875bb7-ee23-43d1-a252-3a6b75ed4811.png)

就是每次新開頁面，默認方案都是空的，我也不知道為甚麼會這樣

**Comment by Mapaler** [comment]
> ![002](https://user-images.githubusercontent.com/99342600/153350434-e4875bb7-ee23-43d1-a252-3a6b75ed4811.png)
> 
> 就是每次新開頁面，默認方案都是空的，我也不知道為甚麼會這樣

其他设置存在，但是只是方案没有吗？

**Comment by JasZero** [comment]
> > ![002](https://user-images.githubusercontent.com/99342600/153350434-e4875bb7-ee23-43d1-a252-3a6b75ed4811.png)
> > 就是每次新開頁面，默認方案都是空的，我也不知道為甚麼會這樣
> 
> 其他设置存在，但是只是方案没有吗？

對呀

**Comment by Mapaler** [comment]
没有复现步骤，目前我也不知道你的问题如何出现的

**Comment by JasZero** [comment]
> 没有复现步骤，目前我也不知道你的问题如何出现的
> 
> 如果你愿意的话，也可以用AnyDesk远程协助看一下

也可以呀

**Comment by Mapaler** [comment]
> 

你可以给我你的远程协助码？

**Comment by JasZero** [comment]
> > 
> 
> 你可以给我你的远程协助码？

730 869 115

**Comment by Mapaler** [comment]
网络断开了

**Comment by JasZero** [comment]
> 网络断开了

https://github.com/Mapaler/PADDashFormation

這個應該怎樣使用?

**Comment by Mapaler** [comment]
> > 网络断开了
> 
> https://github.com/Mapaler/PADDashFormation
> 
> 這個應該怎樣使用?

文档说明里有“立即使用”，里面有在github上挂的网页服务链接，还有我自己搭的网页服务链接。防火墙外的直接用github的就行。

**Comment by Mapaler** [comment]
最初是木宙时代，因为用不来PDC，所以自己做了一个可以分享协力组队的工具。
后来单人成为主流就演变到现在可以进行单人模拟组队，并且用网页链接就可以分享组队和收藏组队，不需要发图片（当然也可以截图给别人）。便于别人收到组队也能立刻自己调整。
后来PDC有二维码分享组队功能后，加入了PDC的二维码支持，可以用通过二维码和PDC交换组队信息。

但是PADDB一直没有字符导出导入组队的功能，所以那个就只能自己手动了。

比如我可以在帖子里这样放一个队伍的链接
[元旦打钱本](https://mapaler.com/PADDashFormation/solo.html?d=%7B%22t%22%3A%222022%E5%85%83%E6%97%A6%E6%89%93%E9%92%B1%22%2C%22d%22%3A%22%25%7Bm4999%7D%E8%BF%9B%E9%97%A84%E5%80%8D%E9%87%91%E5%B8%81%EF%BC%8C%E5%8F%AF%E6%8D%A2%E5%85%B6%E4%BB%96%E9%87%91%E5%B8%81%E9%98%9F%E9%95%BF%EF%BC%9B%E6%AD%A6%E5%99%A8%25%7Bm5068%7D%E6%8F%90%E4%BE%9B%25%7Ba64%7D%EF%BC%8C%E4%B8%8D%E6%98%AF%E5%BF%85%E9%A1%BB%5Cn%25%7Bm5289%7D%2BC%E3%80%81%E8%BF%BD%E6%89%93%EF%BC%8C%E6%AD%A6%E5%99%A8%25%7Bm5656%7D%E6%8D%A2%E9%98%9F%E9%95%BF%5Cn%25%7Bm660%7D%E6%8F%90%E4%BE%9B%25%7Ba21%7D%E5%92%8C%25%7Ba11%7D%EF%BC%9B%E6%AD%A6%E5%99%A8%25%7Bm7541%7DBOSS%E7%A0%B4%E6%97%A0%E6%95%88%5Cn%25%7Bm6864%7D%E6%8F%90%E4%BE%9B%25%7Ba21%7D%E5%92%8C%E7%A0%B4%E5%B1%9E%E5%90%B8%EF%BC%9B%E6%88%96%E6%AD%A6%E5%99%A8%25%7Bm7920%7D%E4%B9%9F%E6%98%AF%E7%A0%B4%E5%B1%9E%E5%90%B8%E5%8F%AF%E8%87%AA%E5%B7%B1%E6%8D%A2%5Cn%25%7Bm7860%7D%E6%8F%90%E4%BE%9B%25%7Ba64%7D%EF%BC%8C%E4%B8%8D%E6%98%AF%E5%BF%85%E9%A1%BB%EF%BC%9B%E6%AD%A6%E5%99%A8%25%7Bm6882%7D%E9%A1%B6%E5%9B%9E%E5%A4%8D%E4%B8%8D%E6%98%AF%E5%BF%85%E9%A1%BB%22%2C%22f%22%3A%5B%5B%5B%5B4999%2C110%2C9%2C99%2C%5B20%2C20%2C11%2C11%5D%2C3%5D%2C%5B660%2C99%2C9%2C99%2C%5B11%2C11%2C11%2C11%2C11%2C11%5D%5D%2C%5B6864%2C110%2C9%2C99%2C%5B11%2C11%2C11%2C11%2C11%2C11%5D%2C3%5D%2C%5B7860%2C110%2C9%2C99%2C%5B20%2C20%2C11%2C11%5D%2C2%5D%2C%5B5289%2C110%2C9%2C99%2C%5B20%2C20%2C11%2C11%5D%2C3%5D%2C%5B4999%2C110%2C9%2C99%2C%5B20%2C20%2C11%2C11%5D%2C3%5D%5D%2C%5B%5B5068%2C99%2C8%2C99%5D%2C%5B7541%2C99%2C8%2C99%5D%2C%5B7920%2C99%2C6%2C99%5D%2C%5B6882%2C99%2C7%2C99%5D%2C%5B5656%2C99%2C6%2C99%5D%2C%5B5068%2C99%2C8%2C99%5D%5D%2C1%2C4%5D%5D%2C%22v%22%3A4%7D)

**Comment by JasZero** [comment]
> 最初是木宙时代，因为用不来PDC，所以自己做了一个可以分享协力组队的工具。 后来单人成为主流就演变到现在可以进行单人模拟组队，并且用网页链接就可以分享组队和收藏组队，不需要发图片（当然也可以截图给别人）。便于别人收到组队也能立刻自己调整。 后来PDC有二维码分享组队功能后，加入了PDC的二维码支持，可以用通过二维码和PDC交换组队信息。
> 
> 但是PADDB一直没有字符导出导入组队的功能，所以那个就只能自己手动了。
> 
> 比如我可以在帖子里这样放一个队伍的链接 [元旦打钱本](https://mapaler.com/PADDashFormation/solo.html?d=%7B%22t%22%3A%222022%E5%85%83%E6%97%A6%E6%89%93%E9%92%B1%22%2C%22d%22%3A%22%25%7Bm4999%7D%E8%BF%9B%E9%97%A84%E5%80%8D%E9%87%91%E5%B8%81%EF%BC%8C%E5%8F%AF%E6%8D%A2%E5%85%B6%E4%BB%96%E9%87%91%E5%B8%81%E9%98%9F%E9%95%BF%EF%BC%9B%E6%AD%A6%E5%99%A8%25%7Bm5068%7D%E6%8F%90%E4%BE%9B%25%7Ba64%7D%EF%BC%8C%E4%B8%8D%E6%98%AF%E5%BF%85%E9%A1%BB%5Cn%25%7Bm5289%7D%2BC%E3%80%81%E8%BF%BD%E6%89%93%EF%BC%8C%E6%AD%A6%E5%99%A8%25%7Bm5656%7D%E6%8D%A2%E9%98%9F%E9%95%BF%5Cn%25%7Bm660%7D%E6%8F%90%E4%BE%9B%25%7Ba21%7D%E5%92%8C%25%7Ba11%7D%EF%BC%9B%E6%AD%A6%E5%99%A8%25%7Bm7541%7DBOSS%E7%A0%B4%E6%97%A0%E6%95%88%5Cn%25%7Bm6864%7D%E6%8F%90%E4%BE%9B%25%7Ba21%7D%E5%92%8C%E7%A0%B4%E5%B1%9E%E5%90%B8%EF%BC%9B%E6%88%96%E6%AD%A6%E5%99%A8%25%7Bm7920%7D%E4%B9%9F%E6%98%AF%E7%A0%B4%E5%B1%9E%E5%90%B8%E5%8F%AF%E8%87%AA%E5%B7%B1%E6%8D%A2%5Cn%25%7Bm7860%7D%E6%8F%90%E4%BE%9B%25%7Ba64%7D%EF%BC%8C%E4%B8%8D%E6%98%AF%E5%BF%85%E9%A1%BB%EF%BC%9B%E6%AD%A6%E5%99%A8%25%7Bm6882%7D%E9%A1%B6%E5%9B%9E%E5%A4%8D%E4%B8%8D%E6%98%AF%E5%BF%85%E9%A1%BB%22%2C%22f%22%3A%5B%5B%5B%5B4999%2C110%2C9%2C99%2C%5B20%2C20%2C11%2C11%5D%2C3%5D%2C%5B660%2C99%2C9%2C99%2C%5B11%2C11%2C11%2C11%2C11%2C11%5D%5D%2C%5B6864%2C110%2C9%2C99%2C%5B11%2C11%2C11%2C11%2C11%2C11%5D%2C3%5D%2C%5B7860%2C110%2C9%2C99%2C%5B20%2C20%2C11%2C11%5D%2C2%5D%2C%5B5289%2C110%2C9%2C99%2C%5B20%2C20%2C11%2C11%5D%2C3%5D%2C%5B4999%2C110%2C9%2C99%2C%5B20%2C20%2C11%2C11%5D%2C3%5D%5D%2C%5B%5B5068%2C99%2C8%2C99%5D%2C%5B7541%2C99%2C8%2C99%5D%2C%5B7920%2C99%2C6%2C99%5D%2C%5B6882%2C99%2C7%2C99%5D%2C%5B5656%2C99%2C6%2C99%5D%2C%5B5068%2C99%2C8%2C99%5D%5D%2C1%2C4%5D%5D%2C%22v%22%3A4%7D)
> 
> 另外怪物信息页面可以当图鉴速查。

這挺不錯哦
順便可以加我好友
主ID:303346670
副ID:359457982, 362157980
