### ISSUE TITLE
请问如何做到下载图片后，用原图片标题来自动重命名？

### ISSUE THREAD

**Issue by f59375543** [Mapaler/PixivUserBatchDownload#99]
设置了半天还是搞不定

**Comment by Mapaler** [comment]
你可以参考 #34

**Comment by f59375543** [comment]
> 你可以参考 #34

懂了，我之前只设置了文本输出模式格式，原来是要修改保存路径

**Comment by Mapaler** [comment]
文本输出模式作用主要是让你测试输出用的。发送自安卓手机发件人: ***@***.*** ***@***.***> 代表 f59375543 ***@***.***>发送时间: 2022年3月6日星期日 19:19收件人: Mapaler/PixivUserBatchDownload抄送: 枫谷剑仙; Comment主题: Re: [Mapaler/PixivUserBatchDownload] 请问如何做到下载图片后，用原图片标题来自动重命名？ (Issue #99)



你可以参考 #34



懂了，我之前只设置了文本输出模式格式，原来是要修改保存路径
